In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9,],[10,11,12]])
c = np.hstack((a,b))
c

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [3]:
d = np.vstack((a,b))
d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
np.concatenate((a,b),0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [5]:
np.concatenate((a,b),1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [6]:
import pandas as pd
df = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
0                    KPCB, Sherpalo Ventures, SoftBank  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  
2             Accel, Sequoia Capital, General Atlantic  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  
..                                                 ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal  

[102 rows x 8 columns]

In [7]:

# df.groupby('Location')["Valuation ($B)"].max()
df_lower = df["Entry"].apply(lambda x: x.upper() if type(x) == str else x.dtype)
df_lower

0      SEP/2011
1      FEB/2012
2      FEB/2013
3      OCT/2014
4      FEB/2015
         ...   
97     JUN/2022
98     JUN/2022
99     JUL/2022
100    AUG/2022
101    SEP/2022
Name: Entry, Length: 102, dtype: object

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   No.                     102 non-null    int64  
 1   Company                 102 non-null    object 
 2   Sector                  102 non-null    object 
 3   Entry Valuation^^ ($B)  102 non-null    float64
 4   Valuation ($B)          102 non-null    float64
 5   Entry                   102 non-null    object 
 6   Location                102 non-null    object 
 7   Select Investors        102 non-null    object 
dtypes: float64(2), int64(1), object(5)
memory usage: 6.5+ KB


In [9]:
df.columns

Index(['No.', 'Company', 'Sector', 'Entry Valuation^^ ($B)', 'Valuation ($B)',
       'Entry', 'Location', 'Select Investors'],
      dtype='object')

In [10]:
df['c'] = df["Entry Valuation^^ ($B)"] + df["Valuation ($B)"]
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors      c  
0                    KPCB, Sherpalo Ventures, SoftBank   2.00  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  38.60  
2             Accel, Sequoia Capital, General Atlantic   2.50  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...   4.20  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  17.70  
..                                                 ...    ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...   2.20  
98         Stakeboat Capital, Gaja Capital, WestBridge   2.00  
99   QED Investors, Matrix Partners India, Sequoia ...   2.60  
100  Lightrock India, Info Edge, Tribe Capital, Tem...   2.46  
101                             Temasek, Motilal Oswal   3.06  

[102 rows x 9 columns]

In [11]:
df['Company']

0                  InMobi
1               Flipkart^
2                Mu Sigma
3               Snapdeal*
4                  PayTM^
              ...        
97                Purplle
98            Leadsquared
99                OneCard
100            Shiprocket
101    Molbio Diagnostics
Name: Company, Length: 102, dtype: object

In [12]:
s = pd.Series([10, 20, 30, None ],index=['A', 'B', 'C', 'D'])
s

A    10.0
B    20.0
C    30.0
D     NaN
dtype: float64

In [13]:
df.dropna()

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors      c  
0                    KPCB, Sherpalo Ventures, SoftBank   2.00  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  38.60  
2             Accel, Sequoia Capital, General Atlantic   2.50  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...   4.20  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  17.70  
..                                                 ...    ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...   2.20  
98         Stakeboat Capital, Gaja Capital, WestBridge   2.00  
99   QED Investors, Matrix Partners India, Sequoia ...   2.60  
100  Lightrock India, Info Edge, Tribe Capital, Tem...   2.46  
101                             Temasek, Motilal Oswal   3.06  

[102 rows x 9 columns]

In [14]:
df.fillna(200)

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors      c  
0                    KPCB, Sherpalo Ventures, SoftBank   2.00  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  38.60  
2             Accel, Sequoia Capital, General Atlantic   2.50  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...   4.20  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  17.70  
..                                                 ...    ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...   2.20  
98         Stakeboat Capital, Gaja Capital, WestBridge   2.00  
99   QED Investors, Matrix Partners India, Sequoia ...   2.60  
100  Lightrock India, Info Edge, Tribe Capital, Tem...   2.46  
101                             Temasek, Motilal Oswal   3.06  

[102 rows x 9 columns]

In [15]:
import pandas as pd

print(pd.__version__)

1.5.3


In [16]:
import pandas as pd
data = [10, 20, 30, 40]
# Create a Series from a list
s = pd.Series(data )


s

0    10
1    20
2    30
3    40
dtype: int64

In [17]:
# Accessing values by index
value = s[1:4:2]
value

1    20
3    40
dtype: int64

In [18]:
a = [10,20,30,40]
a[1:4:2]

[20, 40]

In [19]:
data = {'Name': ['John', 'Emily', 'Michael','anbhu'],
        'Age': [25, 30, 35,60]}


df = pd.DataFrame(data)
df

Name  Age
0     John   25
1    Emily   30
2  Michael   35
3    anbhu   60

In [20]:
df.iloc[1:3,1]

1    30
2    35
Name: Age, dtype: int64

In [21]:
import pandas as pd
df = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
df.iloc[2:4,4:6]

Valuation ($B)     Entry
2             1.5  Feb/2013
3             2.4  Oct/2014

In [22]:
# Example: Creating a DataFrame from a dictionary
import pandas as pd

# Create a DataFrame from a dictionary with default index and columns
data = {'Name': ['John', 'Emily', 'Michael'],
        'Age': [25, 30, 35]}
df = pd.DataFrame(data)
df



Name  Age
0     John   25
1    Emily   30
2  Michael   35

In [23]:
# Create a DataFrame with custom index and columns
df_custom = pd.DataFrame(data, index=['A', 'B', 'C'], columns=['Name', 'Age', 'City'])
df_custom

Name  Age City
A     John   25  NaN
B    Emily   30  NaN
C  Michael   35  NaN

In [24]:
# Example: Creating a DataFrame from a list of lists
import pandas as pd

# Create a DataFrame from a list of lists
data = [['John', 25], ['Emily', 30], ['Michael', 35]]
df = pd.DataFrame(data, columns=['Name', 'Age'])


In [25]:

df

Name  Age
0     John   25
1    Emily   30
2  Michael   35

In [26]:
import pandas as pd
df = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
df.head(20)

No.        Company                       Sector  Entry Valuation^^ ($B)  \
0     1         InMobi          Adtech - Mobile Ads                     1.0   
1     2      Flipkart^                   E-Commerce                     1.0   
2     3       Mu Sigma             SaaS - Analytics                     1.0   
3     4      Snapdeal*                   E-Commerce                     1.8   
4     5         PayTM^  Fintech - Payments & Wallet                     1.7   
5     6       Ola Cabs   Mobility - Ride Aggregator                     1.6   
6     7         Quikr*    Marketplace - Classifieds                     1.0   
7     8        Zomato^                     Foodtech                     1.0   
8     9     ShopClues*                   E-Commerce                     1.1   
9    10          Hike*     Social Media - Messaging                     1.4   
10   11          BYJUS                       Edtech                     1.0   
11   12    PayTM Mall*                   E-Commerce                     1.9   
12   13         Swiggy                     Foodtech                     1.4   
13   14  PolicyBazaar^          Fintech - Insurance                     1.0   
14   15    Freshworks^                   SaaS - CRM                     1.5   
15   16      OYO Rooms     Proptech - Hotel Booking                     4.9   
16   17          Udaan               B2B E-Commerce                     1.0   
17   18       BillDesk       Fintech - B2B Payments                     1.6   
18   19     Delhivery^           Logistics Services                     1.6   
19   20         Rivigo  Logistics Services - Trucks                     1.1   

    Valuation ($B)     Entry             Location  \
0              1.0  Sep/2011  Bangalore/Singapore   
1             37.6  Feb/2012  Bangalore/Singapore   
2              1.5  Feb/2013    Bangalore/Chicago   
3              2.4  Oct/2014                Delhi   
4             16.0  Feb/2015                Noida   
5              7.3  Mar/2015            Bangalore   
6              1.5  Apr/2015            Bangalore   
7              5.4  Sep/2015              Gurgaon   
8              1.1  Jan/2016              Gurgaon   
9              1.4  Aug/2016                Delhi   
10            22.0  Jan/2018            Bangalore   
11             3.0  Apr/2018                Noida   
12            10.7  Jun/2018            Bangalore   
13             2.4  Jun/2018              Gurgaon   
14             3.5  Jul/2018    Chennai/San Mateo   
15             9.6  Sep/2018              Gurgaon   
16             3.1  Sep/2018            Bangalore   
17             1.6  Nov/2018               Mumbai   
18             3.0  Jan/2019              Gurgaon   
19             1.1  Feb/2019              Gurgaon   

                                     Select Investors  
0                   KPCB, Sherpalo Ventures, SoftBank  
1     Accel, Tiger Global, Naspers, SoftBank, Tencent  
2            Accel, Sequoia Capital, General Atlantic  
3   Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4   Saama Capital, Elevation Capital, Alibaba, Ber...  
5   Tiger Global, Matrix Partners, Steadview, Soft...  
6   Matrix Partners, Omidyar Network, Norwest, Kin...  
7   Info Edge, Sequoia Capital, Vy Capital, Alibab...  
8   Nexus Ventures, Helion Ventures, Beenos, Tiger...  
9                      Tiger Global, Tencent, Foxconn  
10  Aarin Capital, Sequoia Capital, Lightspeed Ven...  
11         Elevation Capital, Alibaba, SoftBank, eBay  
12  Accel, Elevation Capital, Norwest, Naspers, Te...  
13  Info Edge, Intel, Inventus Capital, Tiger Glob...  
14  Accel, Tiger Global, Google, Sequoia Capital, ...  
15     Lightspeed Ventures, Sequoia Capital, SoftBank  
16           Lightspeed Ventures, DST Global, Tencent  
17          SIDBI VC, TA Associates, General Atlantic  
18  Nexus Ventures, Multiples PE, Tiger Global, Ca...  
19                  Elevation Capital, Warburg Pincus

In [27]:
df.tail(20)

No.                      Company  \
82    83                  LEAD School   
83    84                    DarwinBox   
84    85                    DealShare   
85    86                      Polygon   
86    87                   ElasticRun   
87    88                     LivSpace   
88    89         XpressBees Logistics   
89    90    Uniphore Software Systems   
90    91                       Hasura   
91    92                   CredAvenue   
92    93             Amagi Media Labs   
93    94     Oxyzo Financial Services   
94    95                    Games24x7   
95    96  Open Financial Technologies   
96    97                PhysicsWallah   
97    98                      Purplle   
98    99                  Leadsquared   
99   100                      OneCard   
100  101                   Shiprocket   
101  102           Molbio Diagnostics   

                                                Sector  \
82                                              Edtech   
83                                           SaaS - HR   
84                        E-Commerce - Social Commerce   
85                         Web3 Infrastructure - Dapps   
86                                  Logistics Services   
87   Interior Design - Modular Kitchens & Home Prod...   
88                                  Logistics Services   
89            SaaS - Conversational Service Automation   
90                            SaaS - Programming Tools   
91                               Marketplace - Lending   
92                          SaaS - Local Ads Targeting   
93                 Fintech - Marketplace - SME Lending   
94                                              Gaming   
95                                  Fintech - Neo Bank   
96                                              Edtech   
97              E-Commerce - Personal Care & Cosmetics   
98                                          SaaS - CRM   
99                              Fintech - Credit Cards   
100                    Aggregator - Logistics Services   
101                           Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
82                     1.10            1.10  Jan/2022               Mumbai   
83                     1.00            1.00  Jan/2022  Hyderabad/Singapore   
84                     1.62            1.70  Jan/2022               Jaipur   
85                    10.00           10.00  Feb/2022            Bangalore   
86                     1.40            1.40  Feb/2022                 Pune   
87                     1.20            1.20  Feb/2022            Bangalore   
88                     1.20            1.20  Feb/2022                 Pune   
89                     2.50            2.50  Feb/2022    Chennai/Palo Alto   
90                     1.00            1.00  Feb/2022            Bangalore   
91                     1.30            1.30  Mar/2022              Chennai   
92                     1.00            1.00  Mar/2022            Bangalore   
93                     1.00            1.00  Mar/2022              Gurgaon   
94                     2.50            2.50  Mar/2022               Mumbai   
95                     1.00            1.00  May/2022            Bangalore   
96                     1.10            1.10  Jun/2022                Noida   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
82   GSV Ventures, WestBridge, Elevar Equity, TPG G...  
83   3ONE4 Capital, Lightspeed Ventures, Sequoia Ca...  
84   Whiteboard Capital, Z3Partners, Alpha Wave Glo...  
85   Coinbase Ventures, Sequoia Capital India, Tige...  


In [28]:
df.shape

(102, 8)

In [29]:
# Example: Using info() to get the summary of a DataFrame
import pandas as pd

# Display the summary of the DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   No.                     102 non-null    int64  
 1   Company                 102 non-null    object 
 2   Sector                  102 non-null    object 
 3   Entry Valuation^^ ($B)  102 non-null    float64
 4   Valuation ($B)          102 non-null    float64
 5   Entry                   102 non-null    object 
 6   Location                102 non-null    object 
 7   Select Investors        102 non-null    object 
dtypes: float64(2), int64(1), object(5)
memory usage: 6.5+ KB


In [30]:
# Example: Using describe() to get descriptive statistics of a DataFrame
import pandas as pd

# Generate descriptive statistics of the DataFrame
df.describe()

No.  Entry Valuation^^ ($B)  Valuation ($B)
count  102.000000              102.000000      102.000000
mean    51.500000                1.547549        3.398020
std     29.588849                1.138013        4.710657
min      1.000000                1.000000        0.568000
25%     26.250000                1.000000        1.200000
50%     51.500000                1.200000        1.850000
75%     76.750000                1.582500        3.475000
max    102.000000               10.000000       37.600000

In [31]:
df.iloc[2:4,1:3]

Company            Sector
2   Mu Sigma  SaaS - Analytics
3  Snapdeal*        E-Commerce

In [32]:
df.loc[2:3,['Sector','Entry']]

Sector     Entry
2  SaaS - Analytics  Feb/2013
3        E-Commerce  Oct/2014

In [33]:
df.iloc[ [1,2,3 ,5,6]]

No.    Company                      Sector  Entry Valuation^^ ($B)  \
1    2  Flipkart^                  E-Commerce                     1.0   
2    3   Mu Sigma            SaaS - Analytics                     1.0   
3    4  Snapdeal*                  E-Commerce                     1.8   
5    6   Ola Cabs  Mobility - Ride Aggregator                     1.6   
6    7     Quikr*   Marketplace - Classifieds                     1.0   

   Valuation ($B)     Entry             Location  \
1            37.6  Feb/2012  Bangalore/Singapore   
2             1.5  Feb/2013    Bangalore/Chicago   
3             2.4  Oct/2014                Delhi   
5             7.3  Mar/2015            Bangalore   
6             1.5  Apr/2015            Bangalore   

                                    Select Investors  
1    Accel, Tiger Global, Naspers, SoftBank, Tencent  
2           Accel, Sequoia Capital, General Atlantic  
3  Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
5  Tiger Global, Matrix Partners, Steadview, Soft...  
6  Matrix Partners, Omidyar Network, Norwest, Kin...

In [34]:
import pandas as pd
df = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
df.head(3)

No.    Company               Sector  Entry Valuation^^ ($B)  \
0    1     InMobi  Adtech - Mobile Ads                     1.0   
1    2  Flipkart^           E-Commerce                     1.0   
2    3   Mu Sigma     SaaS - Analytics                     1.0   

   Valuation ($B)     Entry             Location  \
0             1.0  Sep/2011  Bangalore/Singapore   
1            37.6  Feb/2012  Bangalore/Singapore   
2             1.5  Feb/2013    Bangalore/Chicago   

                                  Select Investors  
0                KPCB, Sherpalo Ventures, SoftBank  
1  Accel, Tiger Global, Naspers, SoftBank, Tencent  
2         Accel, Sequoia Capital, General Atlantic

In [35]:
df[df["Valuation ($B)"].duplicated()]

No.                      Company  \
6     7                       Quikr*   
13   14                PolicyBazaar^   
18   19                   Delhivery^   
19   20                       Rivigo   
22   23               Druva Software   
24   25                   CitiusTech   
25   26                 Ola Electric   
27   28                    Pine Labs   
34   35                       Zenoti   
35   36                    Dailyhunt   
36   37                Glance InMobi   
40   41  Five Star Business Finance^   
44   45                    PharmEasy   
45   46                        Groww   
46   47                    ShareChat   
47   48                      Gupshup   
48   49                    ChargeBee   
51   52                         Zeta   
52   53                 BrowserStack   
53   54                    BlackBuck   
55   56                   OfBusiness   
57   58                   MindTickle   
60   61                     Eruditus   
62   63                      Zetwerk   
64   65                      Apna.co   
65   66                      Vedantu   
68   69                  Rebel Foods   
69   70                     Cardekho   
70   71                         Acko   
71   72                      MyGlamm   
72   73                      CureFit   
73   74                 Mensa Brands   
74   75                     NoBroker   
75   76                       Spinny   
76   77                       Upstox   
77   78                        Slice   
78   79                 Pristyn Care   
80   81                   GlobalBees   
81   82                      Fractal   
82   83                  LEAD School   
83   84                    DarwinBox   
84   85                    DealShare   
86   87                   ElasticRun   
87   88                     LivSpace   
88   89         XpressBees Logistics   
89   90    Uniphore Software Systems   
90   91                       Hasura   
91   92                   CredAvenue   
92   93             Amagi Media Labs   
93   94     Oxyzo Financial Services   
94   95                    Games24x7   
95   96  Open Financial Technologies   
96   97                PhysicsWallah   
97   98                      Purplle   
98   99                  Leadsquared   
99  100                      OneCard   

                                               Sector  Entry Valuation^^ ($B)  \
6                           Marketplace - Classifieds                    1.00   
13                                Fintech - Insurance                    1.00   
18                                 Logistics Services                    1.60   
19                        Logistics Services - Trucks                    1.10   
22                             SaaS - Data Management                    1.00   
24                           IT Services - Healthcare                    1.10   
25                                Mobility - Electric                    1.10   
27                    Fintech - PoS Payment Solutions                    1.60   
34                      SaaS - Salon & Spa Management                    1.00   
35                                     Content - News                    1.00   
36                               Content - Lockscreen                    1.00   
40                                               NBFC                    1.40   
44                       E-Commerce - Online Pharmacy                    1.50   
45                 Fintech - Brokerage & Mutual Funds                    1.00   
46                                       Social Media                    2.10   
47                           Conversational Messaging                    1.40   
48               SaaS - Subscription Billing Solution                    1.40   
51                   Fintech - API - Banking Products                    1.40   
52                            SaaS - Software Testing                    4.00   
53                                 Logistics Services                    1.00   
55                    

In [36]:
df.loc[df["No."]  <= 5,"No."] = None
df.isnull().sum()

No.                       5
Company                   0
Sector                    0
Entry Valuation^^ ($B)    0
Valuation ($B)            0
Entry                     0
Location                  0
Select Investors          0
dtype: int64

In [37]:
df[ "No."]

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...  
97      98.0
98      99.0
99     100.0
100    101.0
101    102.0
Name: No., Length: 102, dtype: float64

In [38]:
df.columns

Index(['No.', 'Company', 'Sector', 'Entry Valuation^^ ($B)', 'Valuation ($B)',
       'Entry', 'Location', 'Select Investors'],
      dtype='object')

In [39]:
df[ (df["No."] <10)    & (df["Valuation ($B)"] <= 5)]

No.     Company                     Sector  Entry Valuation^^ ($B)  \
6  7.0      Quikr*  Marketplace - Classifieds                     1.0   
8  9.0  ShopClues*                 E-Commerce                     1.1   

   Valuation ($B)     Entry   Location  \
6             1.5  Apr/2015  Bangalore   
8             1.1  Jan/2016    Gurgaon   

                                    Select Investors  
6  Matrix Partners, Omidyar Network, Norwest, Kin...  
8  Nexus Ventures, Helion Ventures, Beenos, Tiger...

In [40]:
df[ (df["No."] == 10)  | (df["No."] == 9) ]

No.     Company                    Sector  Entry Valuation^^ ($B)  \
8   9.0  ShopClues*                E-Commerce                     1.1   
9  10.0       Hike*  Social Media - Messaging                     1.4   

   Valuation ($B)     Entry Location  \
8             1.1  Jan/2016  Gurgaon   
9             1.4  Aug/2016    Delhi   

                                    Select Investors  
8  Nexus Ventures, Helion Ventures, Beenos, Tiger...  
9                     Tiger Global, Tencent, Foxconn

In [41]:
aa = df[ df["No."].isin([10,9]) ]
aa

No.     Company                    Sector  Entry Valuation^^ ($B)  \
8   9.0  ShopClues*                E-Commerce                     1.1   
9  10.0       Hike*  Social Media - Messaging                     1.4   

   Valuation ($B)     Entry Location  \
8             1.1  Jan/2016  Gurgaon   
9             1.4  Aug/2016    Delhi   

                                    Select Investors  
8  Nexus Ventures, Helion Ventures, Beenos, Tiger...  
9                     Tiger Global, Tencent, Foxconn

In [42]:
df["c"]  = df["Company" ] + df["Sector"]
df.head(3)

No.    Company               Sector  Entry Valuation^^ ($B)  \
0  NaN     InMobi  Adtech - Mobile Ads                     1.0   
1  NaN  Flipkart^           E-Commerce                     1.0   
2  NaN   Mu Sigma     SaaS - Analytics                     1.0   

   Valuation ($B)     Entry             Location  \
0             1.0  Sep/2011  Bangalore/Singapore   
1            37.6  Feb/2012  Bangalore/Singapore   
2             1.5  Feb/2013    Bangalore/Chicago   

                                  Select Investors                          c  
0                KPCB, Sherpalo Ventures, SoftBank  InMobiAdtech - Mobile Ads  
1  Accel, Tiger Global, Naspers, SoftBank, Tencent        Flipkart^E-Commerce  
2         Accel, Sequoia Capital, General Atlantic   Mu SigmaSaaS - Analytics

In [43]:
# df.drop("No.",1,inplace=True)
# df

In [44]:
# df.loc[df['No.'] <10, "Sector"] = 15
# df

In [45]:
df['ee'] = df['No.'].apply(lambda x: x * 10)
df

No.             Company                                  Sector  \
0      NaN              InMobi                     Adtech - Mobile Ads   
1      NaN           Flipkart^                              E-Commerce   
2      NaN            Mu Sigma                        SaaS - Analytics   
3      NaN           Snapdeal*                              E-Commerce   
4      NaN              PayTM^             Fintech - Payments & Wallet   
..     ...                 ...                                     ...   
97    98.0             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99.0         Leadsquared                              SaaS - CRM   
99   100.0             OneCard                  Fintech - Credit Cards   
100  101.0          Shiprocket         Aggregator - Logistics Services   
101  102.0  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  \
0                    KPCB, Sherpalo Ventures, SoftBank   
1      Accel, Tiger Global, Naspers, SoftBank, Tencent   
2             Accel, Sequoia Capital, General Atlantic   
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...   
4    Saama Capital, Elevation Capital, Alibaba, Ber...   
..                                                 ...   
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...   
98         Stakeboat Capital, Gaja Capital, WestBridge   
99   QED Investors, Matrix Partners India, Sequoia ...   
100  Lightrock India, Info Edge, Tribe Capital, Tem...   
101                             Temasek, Motilal Oswal   

                                                 c      ee  
0                        InMobiAdtech - Mobile Ads     NaN  
1                              Flipkart^E-Commerce     NaN  
2                         Mu SigmaSaaS - Analytics     NaN  
3                              Snapdeal*E-Commerce     NaN  
4                PayTM^Fintech - Payments & Wallet     NaN  
..                                             ...     ...  
97   PurplleE-Commerce - Personal Care & Cosmetics   980.0  
98                           LeadsquaredSaaS - CRM   990.0  
99                   OneCardFintech - Credit Cards  1000.0  
100      ShiprocketAggregator - Logistics Services  1010.0  
101     Molbio DiagnosticsHealthtech - Diagnostics  1020.0  

[102 rows x 10 columns]

In [46]:
# Example: Conditional selection using string methods
import pandas as pd

# Select rows where a column's value contains a specific substring
subset = aa[aa['Location'].str.startswith('Delh')]
subset
# Select rows where a column's value starts with a specific string
#subset = df[df['column'].str.startswith('string')]

No. Company                    Sector  Entry Valuation^^ ($B)  \
9  10.0   Hike*  Social Media - Messaging                     1.4   

   Valuation ($B)     Entry Location                Select Investors  
9             1.4  Aug/2016    Delhi  Tiger Global, Tencent, Foxconn

In [47]:
concatenated_df = pd.concat([df["No."], df["Sector"], df["Entry"]], axis=1)
concatenated_df

No.                                  Sector     Entry
0      NaN                     Adtech - Mobile Ads  Sep/2011
1      NaN                              E-Commerce  Feb/2012
2      NaN                        SaaS - Analytics  Feb/2013
3      NaN                              E-Commerce  Oct/2014
4      NaN             Fintech - Payments & Wallet  Feb/2015
..     ...                                     ...       ...
97    98.0  E-Commerce - Personal Care & Cosmetics  Jun/2022
98    99.0                              SaaS - CRM  Jun/2022
99   100.0                  Fintech - Credit Cards  Jul/2022
100  101.0         Aggregator - Logistics Services  Aug/2022
101  102.0                Healthtech - Diagnostics  Sep/2022

[102 rows x 3 columns]

In [48]:
concatenated_df

No.                                  Sector     Entry
0      NaN                     Adtech - Mobile Ads  Sep/2011
1      NaN                              E-Commerce  Feb/2012
2      NaN                        SaaS - Analytics  Feb/2013
3      NaN                              E-Commerce  Oct/2014
4      NaN             Fintech - Payments & Wallet  Feb/2015
..     ...                                     ...       ...
97    98.0  E-Commerce - Personal Care & Cosmetics  Jun/2022
98    99.0                              SaaS - CRM  Jun/2022
99   100.0                  Fintech - Credit Cards  Jul/2022
100  101.0         Aggregator - Logistics Services  Aug/2022
101  102.0                Healthtech - Diagnostics  Sep/2022

[102 rows x 3 columns]

In [49]:
df1 = df["No."]
df1

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
       ...  
97      98.0
98      99.0
99     100.0
100    101.0
101    102.0
Name: No., Length: 102, dtype: float64

In [50]:
df["No."] > 20

0      False
1      False
2      False
3      False
4      False
       ...  
97      True
98      True
99      True
100     True
101     True
Name: No., Length: 102, dtype: bool

In [51]:
# import pandas as pd

# # Select rows where a column meets a specific condition
# subset = df[df['column'] > 10]

# # Select rows based on multiple conditions
# subset = df[(df['column1'] > 10) & (df['column2'] < 20)]

In [52]:
# sorted_df = df.sort_values(by=['column1', 'column2'], ascending=[True, False])

# sorted_df = df.sort_values(ascending=[True, False],by=['column1', 'column2'])

# sorted_df = df.sort_values(['column1', 'column2'], [True, False])

# sorted_df = df.sort_values([True, False],['column1', 'column2'])

In [53]:
import numpy as np
x = np.zeros((4, 4))


print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [54]:
x[::2, 1::2] = 1
x

array([[0., 1., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 1.],
       [0., 0., 0., 0.]])

In [55]:
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [56]:
import pandas as pd
df = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
0                    KPCB, Sherpalo Ventures, SoftBank  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  
2             Accel, Sequoia Capital, General Atlantic  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  
..                                                 ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal  

[102 rows x 8 columns]

In [57]:
# cutsom functions for aggregating group by
import numpy as np
def fun(x):
    ans = np.sum(x) + 1
    return ans

grouped = df.groupby('Sector').agg({'Entry Valuation^^ ($B)': 'sum'})
grouped

Entry Valuation^^ ($B)
Sector                                                         
Adtech - Mobile Ads                                        1.00
Aggregator - Consumer Brands                               2.30
Aggregator - Logistics Services                            1.23
B2B E-Commerce                                             1.00
B2B E-Commerce - Construction Materials                    1.00
...                                                         ...
SaaS - Software Testing                                    4.00
SaaS - Subscription Billing Solution                       1.40
Social Media                                               2.10
Social Media - Messaging                                   1.40
Web3 Infrastructure - Dapps                               10.00

[75 rows x 1 columns]

In [58]:

grouped = df.groupby('Sector').agg({ 'Entry Valuation^^ ($B)': fun})
grouped

Entry Valuation^^ ($B)
Sector                                                         
Adtech - Mobile Ads                                        2.00
Aggregator - Consumer Brands                               3.30
Aggregator - Logistics Services                            2.23
B2B E-Commerce                                             2.00
B2B E-Commerce - Construction Materials                    2.00
...                                                         ...
SaaS - Software Testing                                    5.00
SaaS - Subscription Billing Solution                       2.40
Social Media                                               3.10
Social Media - Messaging                                   2.40
Web3 Infrastructure - Dapps                               11.00

[75 rows x 1 columns]

In [59]:
filtered_groups = df.groupby('Location').agg({'Entry Valuation^^ ($B)': 'sum','Sector': 'count'})
filtered_groups

Entry Valuation^^ ($B)  Sector
Location                                               
Bangalore                                 56.70      34
Bangalore/Chicago                          1.00       1
Bangalore/San Francisco                    4.60       3
Bangalore/Singapore                        3.00       3
Chennai                                    2.70       2
Chennai/Palo Alto                          2.50       1
Chennai/San Francisco                      1.40       1
Chennai/San Mateo                          1.50       1
Delhi                                     11.53       7
Goa                                        1.53       1
Gurgaon                                   20.37      14
Hyderabad/Bellevue                         1.00       1
Hyderabad/Singapore                        1.00       1
Jaipur                                     2.82       2
Mumbai                                    18.30      12
Mumbai/Dublin                              4.00       1
Mumbai/New York                            1.00       1
Mumbai/Princeton                           1.10       1
Mumbai/San Francisco                       1.40       1
Mumbai/Singapore                           3.20       1
Noida                                      6.30       4
Noida/San Francisco                        1.30       1
Noida/Singapore                            1.00       1
Pune                                       5.60       4
Pune/Bellevue                              1.00       1
Pune/Sunnyvale                             1.00       1
Thane                                      1.00       1

In [60]:
# filtered_group = df.filter(lambda x: len(x) > 13)
# # .agg({'Entry Valuation^^ ($B)': 'sum','Sector': 'count'})
# filtered_group