In [1]:
a = 6
print(a)
print("---")
# a = 
print(a)

6
---
6


In [2]:
a = 7

# data types

In [3]:
abhi = 6

print(abhi)

6


In [4]:
type(abhi)

int

In [5]:
swa = 6.5
type(swa)

float

In [6]:
pra = 3 + 2j

type(pra)

complex

In [7]:
x = "sush"
type(x)

str

In [8]:
z = 44 - 5 - 14
z
type(z)

int

In [9]:
y = "44-5-14"
y

'44-5-14'

In [10]:
type(y)

str

# type casting

In [11]:
a = 6.5
type(a)

float

In [12]:
b = int(a)
b

6

In [13]:
type(b)

int

In [14]:
c = float(b)
c

6.0

In [15]:
type(c)

float

In [16]:
g = "66"
h = "7"

g + h

'667'

In [17]:
i = 66
j = 7
i + j

73

In [18]:
p = "66"
q = 7
# "667"
p + str(q)

'667'

In [19]:
p = "66"
q = 7
int(p) + q

73

In [20]:
a = 7
b = 8
b

8

In [21]:
a,b = 7,8
b

8

In [22]:
abhi7 = 7
abhi7

7

In [23]:
x = 4       # x is of type int
x = "Sally" # x is now of type str
print(x)

Sally


In [24]:
x = 4       # x is of type int
print(x)
x = "Sally" # x is now of type str


4


In [25]:
# o/p
a= 7
print(a)

7


In [26]:
# a = int(input())
# print(a+1)

In [27]:
a = 6 + 7
a

13

In [28]:
b = "da" + str(50)
b

'da50'

In [29]:
x = 5
y = "John"
print(x, y)

5 John


In [30]:
a = 6 
a = 7

# data  structures


# List  [ ] 

In [31]:
a = [11,28,34,45,57]
a[0]



11

In [32]:
a[4]

57

In [33]:
a

[11, 28, 34, 45, 57]

In [34]:
a[-1]

57

In [35]:
a[-5]

11

In [36]:
a[1:4]

[28, 34, 45]

In [37]:
a = [10,20,30,40 ,50,60,70,80,90]

In [38]:
# 2 property index - list = zero -index 
a[1:8]

[20, 30, 40, 50, 60, 70, 80]

In [39]:
a[1:8:2]

[20, 40, 60, 80]

In [40]:
a[1:-1:3]

[20, 50, 80]

In [41]:
# property of 1 of list 
# mutabilty

a 

[10, 20, 30, 40, 50, 60, 70, 80, 90]

In [42]:
a[0]

10

In [43]:
a[0] = 900
a

[900, 20, 30, 40, 50, 60, 70, 80, 90]

In [44]:
type(a)

list

# tuple  (  )

In [45]:
b = (10,20,30,40,50)
b[0]

10

In [46]:
type(b)

tuple

In [47]:
b[4]

50

In [48]:
b[-1]

50

In [49]:
# property 2 of tuple - zero index 

In [50]:
# b[0] = 10

In [51]:
# property immutabilty - ypu cant change elements in a list

In [52]:
# set 

{ }

In [53]:
c = {10,20,30,40}

In [54]:
c

{10, 20, 30, 40}

In [55]:
d = {10,20,10,20}

In [56]:
d

{10, 20}

In [57]:
# # property 1 

# unique elements only 

In [58]:
# property 
# there is no index in set 

d

{10, 20}

In [59]:
# d[0]

# dictionary  ( ) 

In [60]:
t = { "beautiful"   : "swapna is a beautiful women",
    "smart" : "tayyab is a smart person",
    "clever" : "parth is clever"}

In [61]:
# property index - key index

In [62]:
t.keys()

dict_keys(['beautiful', 'smart', 'clever'])

In [63]:
t["beautiful"]

'swapna is a beautiful women'

In [64]:
t["clever"]

'parth is clever'

In [65]:
t.keys()

dict_keys(['beautiful', 'smart', 'clever'])

In [66]:
t.values()

dict_values(['swapna is a beautiful women', 'tayyab is a smart person', 'parth is clever'])

In [67]:
t.items()

dict_items([('beautiful', 'swapna is a beautiful women'), ('smart', 'tayyab is a smart person'), ('clever', 'parth is clever')])

In [68]:
ch = { "c1" :
                   {"c1.1" :  "chapter1.1",
                    
                    "c1.2" :  
                             {"c1.2.1" : "chapter mlv",
                              "c1.2.2" : [10,20,30,40]},
                    
                    "c1.3" :  "chapter1.3"},
     "c2" : "chapter2",
     "c3" : "chapter3"}

list(str(ch["c1"]["c1.2"]["c1.2.2"][3]))[0]

'4'

In [69]:
ch["c1"]["c1.2"]["c1.2.2"][0]

10

In [70]:
ch["c3"] = "sush"

In [71]:
len(ch.items())

3

In [72]:
ch

{'c1': {'c1.1': 'chapter1.1',
  'c1.2': {'c1.2.1': 'chapter mlv', 'c1.2.2': [10, 20, 30, 40]},
  'c1.3': 'chapter1.3'},
 'c2': 'chapter2',
 'c3': 'sush'}

# type
int()
float()
str()

# data structure casting
## list()  tuple() set()  dict()

In [73]:
a = [10,20,30]
type(a)

list

In [74]:
b = tuple(a)
b

(10, 20, 30)

In [75]:
type(b)

tuple

In [76]:
gg = ("sush@gmail.com",2564856855)
# gg[0] = "sush@outlook.com"

In [77]:
gg = list(gg)
gg

['sush@gmail.com', 2564856855]

In [78]:
type(gg)

list

In [79]:
gg[0] = "sush@outlook.com"
gg

['sush@outlook.com', 2564856855]

In [80]:
gg = tuple(gg)
gg

('sush@outlook.com', 2564856855)

In [81]:
gg = ("sush@gmail.com",2564856855)
gg = list(gg)
gg[0] = "sush@outlook.com"
gg = tuple(gg)
gg

('sush@outlook.com', 2564856855)

In [82]:
a = [10,20,30,10]
a = list(set(a))
a

[10, 20, 30]

In [83]:
a = list(set(a))
a

[10, 20, 30]

In [84]:
c = { 10,20,30,30}
c 



{10, 20, 30}

In [85]:
thislist = ["apple", "banana", "cherry"]
print(len(thislist))

3


In [86]:
thislist = list(("apple", "banana", "cherry")) # note the double round-brackets
print(thislist)

['apple', 'banana', 'cherry']


In [87]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[:])

['apple', 'banana', 'cherry', 'orange', 'kiwi', 'melon', 'mango']


In [88]:
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[-4:-1])

['orange', 'kiwi', 'melon']


In [89]:
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"
print(thislist)

['apple', 'blackcurrant', 'cherry']


In [90]:
fruits = ['apple', 'banana', 'cherry']
fruits.append("orange")
fruits

['apple', 'banana', 'cherry', 'orange']

In [91]:
fruits = ['apple', 'banana', 'cherry', 'orange']

fruits.clear()

In [92]:
fruits 

[]

In [93]:
tay = ['sush', 'sush', 'cherry']

tay.count("sush")

2

In [94]:
fruits = ['apple', 'banana', 'cherry']

points = (1, 4, 5, 9)

fruits.extend(points)
fruits[3]

1

In [95]:
fruits = ['apple', 'banana', 'cherry']

points = (1, 4, 5, 9)

fruits.append(points)
fruits

['apple', 'banana', 'cherry', (1, 4, 5, 9)]

In [96]:
fruits[3]

(1, 4, 5, 9)

In [97]:
fruits = ['c001asha', 'coo2swapna', 'c001asha']

fruits.index("c001asha")

0

In [98]:
fruits = ['apple', 'banana', 'cherry']

fruits.insert(2, "orange")
fruits

['apple', 'banana', 'orange', 'cherry']

In [99]:
fruits = ['apple', 'banana', 'cherry']
a = fruits.pop(0)
a

'apple'

In [100]:
fruits = ['apple', 'banana', 'cherry']
a = fruits.index("apple")
a

0

In [101]:
fruits = ['banana', "apple",'banana', 'banana']

fruits.remove("banana")
fruits 

# ctr a
#  ctr /

['apple', 'banana', 'banana']

In [102]:
fruits = ['apple', 'banana', 'cherry']

fruits.reverse()
fruits

['cherry', 'banana', 'apple']

In [103]:
a= [20,11,9,30]
a

[20, 11, 9, 30]

In [104]:
a.sort(reverse = True)
a

[30, 20, 11, 9]

In [105]:
d = [10,20,30]
d.append([40,50,60])
d

[10, 20, 30, [40, 50, 60]]

In [106]:
e = [10,20,30]
e.extend([40,50,60])
e

[10, 20, 30, 40, 50, 60]

In [107]:
a = [2,3,4,4]
a = list(set(a))
a

[2, 3, 4]

In [108]:
if 9 > 6 : 
    print("yes")
    print("tayyab")
    
print("prasad")


yes
tayyab
prasad


In [109]:
if 9 > 16 : 
    print("yes")
    print("tayyab")
    
print("prasad")

prasad


In [110]:
# select *
#             from table1

In [111]:
marks = 80
gender = "female"


if marks > 75 :  
    if gender == "male" :
        print("the boy got distinction")
    else :
        print("the girl got distinction")        
    print("distinction")
elif marks > 50 :
    print("pass")
else :
    print("fail")

the girl got distinction
distinction


In [112]:
salary = 100

while salary > 90 :
    print("mlv",salary )
    salary = salary - 3

mlv 100
mlv 97
mlv 94
mlv 91


In [113]:
for i in  range(10,20,3) :
    print(i)
    print("----")

10
----
13
----
16
----
19
----


In [114]:
for i in  [10,13,16,19] :
    print(i)
    print("----")
    print("husna")

10
----
husna
13
----
husna
16
----
husna
19
----
husna


In [115]:
a = [10,20,30,40,50]

for  abhi  in a :
    print("the element is ",abhi)

the element is  10
the element is  20
the element is  30
the element is  40
the element is  50


In [116]:
a = [10,20,30,40,50]

for abhi in range(len(a)) : # [ 0,1,2,3,4]
    print("the element is ",a[abhi])
    

the element is  10
the element is  20
the element is  30
the element is  40
the element is  50


In [117]:
for i in range(1,5):
    print(i)

1
2
3
4


### 

In [118]:
fruits = {"apple", "banana", "cherry"}

fruits.add("orange")

print(fruits)

{'banana', 'orange', 'cherry', 'apple'}


In [119]:
fruits = {"apple", "banana", "cherry"}

fruits.clear()

fruits.add("tayyab")

print(fruits)

{'tayyab'}


In [120]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.difference(y)

print(z)

{'banana', 'cherry'}


In [121]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = y.intersection(x)

print(z)

{'apple'}


In [122]:
x = {"apple", "google", "cherry"}
y = {"google", "microsoft", "facebook"}

z = x.isdisjoint(y)

print(z)


False


In [123]:
x = {"a", "b", "h"}
y = {"f", "e", "d", "c", "b", "a"}

z = x.issubset(y)

print(z)

False


In [124]:
x = {"f", "e", "d", "c", "b", "a"}
y = {"a", "b", "z"}

z = x.issuperset(y)

print(z)

False


In [125]:
fruits = {"apple", "banana", "cherry"}

fruits.pop()

print(fruits)

{'cherry', 'apple'}


In [126]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

z = x.union(y)

print(x)

{'banana', 'cherry', 'apple'}


In [127]:
x = {"apple", "banana", "cherry"}
y = {"google", "microsoft", "apple"}

x.update(y)

print(x)

{'microsoft', 'banana', 'cherry', 'apple', 'google'}


In [128]:
x = ('key 1', 'key 2', 'key 3')
y = "sush"

thisdict = dict.fromkeys(x, y)

print(thisdict)

{'key 1': 'sush', 'key 2': 'sush', 'key 3': 'sush'}


In [129]:
thisdict  = { "key 1" : "sush",
            "key 2" : "sush",
            "key 3 " : "sush"}
thisdict

{'key 1': 'sush', 'key 2': 'sush', 'key 3 ': 'sush'}

In [130]:
x = ('st 1', 'st 2', 'st 3')
y = 0 

In [131]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.get("model")



'Mustang'

In [132]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
car["model"]

'Mustang'

In [133]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.keys()

dict_keys(['brand', 'model', 'year'])

In [134]:
car.values()

dict_values(['Ford', 'Mustang', 1964])

In [135]:
car.items()

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964)])

In [136]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.pop("model")

print(car)

{'brand': 'Ford', 'year': 1964}


In [137]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.popitem()

print(car)

{'brand': 'Ford', 'model': 'Mustang'}


In [138]:
car = {
  "brand": "Ford",
    "model" : None ,

  "year": 1964
}

x = car.setdefault("model", "Bronco")

print(x)

None


In [139]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}


car.update({"color": "White"})
print(car)



{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'White'}


In [140]:
# *

In [141]:
print("*")

*


In [142]:
# *
# **

In [143]:
print("*")
print("**")

*
**


In [144]:
# *
# **
# ***
# ****

In [145]:
for i in range(4) :
    print(" "*(3-i),end="")
    print("*"* (i+1))
#     print("--")
for j in range(3):
    print(" "*(j+1),end="")
    print("*"*(3-j))

   *
  **
 ***
****
 ***
  **
   *


In [146]:
#    *
#   ***
#  *****
# *******

#  *****
#   ***
#    *

In [147]:
# *
# ***
# *****
# *******


# *****
# ***
# *

In [148]:
for i in range(4):
    print("*"* ((2*i)+1))
for j in range(3):
    print("*")

*
***
*****
*******
*
*
*


In [149]:
#     *
#    ***
#   *****
#  *******
# *********
#  *******
#   *****
#    ***
#     *

In [150]:
n =25

for i in range(n):
    print(" "*(n-1-i),end="")
    print("*"*((2*i)+1))
for j in range(n-1):
    print(" "*(j+1),end="")
    print("*"*((2*(n-2-j))+1))

                        *
                       ***
                      *****
                     *******
                    *********
                   ***********
                  *************
                 ***************
                *****************
               *******************
              *********************
             ***********************
            *************************
           ***************************
          *****************************
         *******************************
        *********************************
       ***********************************
      *************************************
     ***************************************
    *****************************************
   *******************************************
  *********************************************
 ***********************************************
*************************************************
 ***********************************************
 

# 

In [151]:
#    *    
#   * *
#  *   *
# *     *
#  *   *
#   * *


#    *

In [152]:
n = 11
# n = 4
print(" "*(n-1),"*")
for i in range((n-1)):
    print(" "*(n-2-i),"*"+" "*((2*i )+1)+"*")
for j in range(n-2):
    print(" "*(j+1),"*"+" "*((2*(n-2-j))-1)+"*")
    

    
print(" "*(n-1),"*")

           *
          * *
         *   *
        *     *
       *       *
      *         *
     *           *
    *             *
   *               *
  *                 *
 *                   *
  *                 *
   *               *
    *             *
     *           *
      *         *
       *       *
        *     *
         *   *
          * *
           *


In [153]:
# 1
# 1 1
# 1 1 1
# 1 1 1 1
# 1 1 1 1 1

In [154]:
for i in range(5):
    print("1 "*(i+1))

1 
1 1 
1 1 1 
1 1 1 1 
1 1 1 1 1 


In [155]:
# 1
# 1 2
# 1 2 3
# 1 2 3 4
# 1 2 3 4 5

In [156]:
for i in range(5):
    for j in range(i+1) :
        print(j+1,end=" ")
    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [157]:
#       1
#     1 2 1
#   1 2 3 2 1 
# 1 2 3 4 3 2 1
#   1 2 3 2 1
#     1 2 1
#       1

In [158]:
n = 8
# 4
for i in range(n):
    print(" "*(2*(n-1-i)),end="")
    for j in range(i+1):
        print(j+1 ,end=" ")
    for k in range(i-1,-1,-1):
        print(k+1 ,end=" ")
    print()
for p in range(n-1) : # 0 13
    print(" "*(2*(p+1)),end="")
    for q in range(n-1-p) :
        print(q+1,end=" ")        
    for r in range(n-p-3,-1,-1):
        print(r+1,end=" ")
    print()

              1 
            1 2 1 
          1 2 3 2 1 
        1 2 3 4 3 2 1 
      1 2 3 4 5 4 3 2 1 
    1 2 3 4 5 6 5 4 3 2 1 
  1 2 3 4 5 6 7 6 5 4 3 2 1 
1 2 3 4 5 6 7 8 7 6 5 4 3 2 1 
  1 2 3 4 5 6 7 6 5 4 3 2 1 
    1 2 3 4 5 6 5 4 3 2 1 
      1 2 3 4 5 4 3 2 1 
        1 2 3 4 3 2 1 
          1 2 3 2 1 
            1 2 1 
              1 


# for i in range(4):
    print(i, end=" ")

In [159]:
for i in range(3,-1,-1):
    print(i, end=" ")

3 2 1 0 

In [160]:
# 0  

# 0 1  

# 0 2 4  

# 0 3 6 9  

# 0 4 8 12 16  

# 0 5 10 15 20 25  

# 0 6 12 18 24 30 36

In [161]:
n = 15
# 6
for i in range(n+1):
    for j in range(i+1):
        print(j*i,end=" ")
    print()

0 
0 1 
0 2 4 
0 3 6 9 
0 4 8 12 16 
0 5 10 15 20 25 
0 6 12 18 24 30 36 
0 7 14 21 28 35 42 49 
0 8 16 24 32 40 48 56 64 
0 9 18 27 36 45 54 63 72 81 
0 10 20 30 40 50 60 70 80 90 100 
0 11 22 33 44 55 66 77 88 99 110 121 
0 12 24 36 48 60 72 84 96 108 120 132 144 
0 13 26 39 52 65 78 91 104 117 130 143 156 169 
0 14 28 42 56 70 84 98 112 126 140 154 168 182 196 
0 15 30 45 60 75 90 105 120 135 150 165 180 195 210 225 


In [162]:
# 1 

# 3 3 

# 5 5 5 

# 7 7 7 7 

# 9 9 9 9 9

In [163]:

n = 5
for i in range(n):
    for j in range(i+1):
        print((2*i)+1,end=" ")
    print()

1 
3 3 
5 5 5 
7 7 7 7 
9 9 9 9 9 


In [164]:
# ******
#     *
#    *
#   *
#  *
# ******

In [165]:
n = 12
print("*"*n)
for i in range(n-2):
    print(" "*(n-2-i),end="")
    print("*")
print("*"*n)

************
          *
         *
        *
       *
      *
     *
    *
   *
  *
 *
************


In [166]:
# 1 2 3 * * * N
#           *
#         *
#       *
#     3
#   2
# 1 2 3 * * * N


In [167]:
for i in range(3):
    print(i+1, end=" ")
for j in range(3):
    print("* ",end="")
print("N")

print()
for k in range(3):
    print(" "*(2*(5-k)),end="")
    print("*")
for m in range(2):
    print(" "*(2*(2-m)),end="")
    print(3-m)   
    
    
for i in range(3):
    print(i+1, end=" ")
for j in range(3):
    print("* ",end="")
print("N")

1 2 3 * * * N

          *
        *
      *
    3
  2
1 2 3 * * * N


In [168]:
m1 = 80
m2 = 40
student = "prasad"


if m1 > 50 and m2 > 50 :
    print(student , " is eligible")
else :
    print(student," is not eligible")

prasad  is not eligible


In [169]:
m1 = 70
m2 = 80
student = "sushmitha"
if m1 > 50 and m2 > 50 :
    print(student , " is eligible")
else :
    print(student," is not eligible")


sushmitha  is eligible


In [170]:
def level(a,b,student) :
    c = a+b
    print(student," got ", c ," marks")

In [171]:
level(40,50,"prasad")

prasad  got  90  marks


In [172]:
level(80,50,"sush")

sush  got  130  marks


In [173]:


def marks (m1,m2,student="def"):
    print(m1)
    if m1 > 50 and m2 > 50 :
        print(student , " is eligible")
    else :
        print(student," is not eligible")
        
        
        
print("--")

        
        
        
        
marks(m1=50,m2=40)

--
50
def  is not eligible


In [174]:
marks(student = "swapna",m2=90,m1=80)

80
swapna  is eligible


In [175]:
# marks("student",90,80)

In [176]:
marks(30,30,"parth")

30
parth  is not eligible


In [177]:
marks(90,90,"tayyab")

90
tayyab  is eligible


In [178]:


def marks (m1=0,m2=0,student="st") :
    print(m1)
    if m1 > 50 and m2 > 50 :
        print(student , " is eligible")
    else :
        print(student," is not eligible")
        
marks()

0
st  is not eligible


In [179]:
# print 
# return

In [180]:
def add (a,b) :
    c = a+b
    return c

p= add(5,10)
print("----",p)

---- 15


In [181]:
def add (a,b) :
    c = a+b
    print(c)

p = add(5,10)
print("----",p)

15
---- None


In [182]:
# if add(5,10 ) > 10 :
#     print("eligible")
# else :
#     print("not eligible")

In [183]:
def add (a,b) :
    c = a+b
    return c

add(5,10)

15

In [184]:
add = lambda  a,b : a+b
add(7,10)

17

In [185]:
add(10,20)

30

In [186]:
# list comprehenison :  list + for loop / any loop

In [187]:
a = [20 ,25,30,35]

even = []

for i in a :
    if i%2 == 0 :
        even.append(i)
        
        
        
even

[20, 30]

In [188]:
a = [20 ,25,30,35]

even = [  i  for i in a  if i%2 == 0   ]       
        
        
even

[20, 30]

In [189]:
a = [20 ,25,30,35]

even = { i: "Abhi"  for i in a  if i%2 == 0   }       
        
        
even

{20: 'Abhi', 30: 'Abhi'}

In [190]:
# break continue pass

In [191]:
def add(a,b):
    pass
    
add(8,9)

In [192]:
for i in range(5):
    if i == 3 :
        break
    print(i)

0
1
2


In [193]:
for i in range(5):
    if i == 3 :
        continue
    print(i)

0
1
2
4


In [194]:
# \n = new line \t tab

In [195]:
print("mlv")
print("prasad")

mlv
prasad


In [196]:
print("mlv\nprasad")

mlv
prasad


In [197]:
print("mlv    prasad    is    a    good    boy")

mlv    prasad    is    a    good    boy


In [198]:
print("mlv\tprasad\tis\ta\tgood\tboy")

mlv	prasad	is	a	good	boy


In [199]:
# * * * * *
# * * * *
# * * * 
# * * 
# *

In [200]:
for i in range(5):
    print("* "*(5-i))

* * * * * 
* * * * 
* * * 
* * 
* 


## filter
## reduce
## map
## zip

In [201]:
# filter 

In [202]:
a  =  [10,11,12,13,14,15,16]


b = []
for i in range(len(a)) :
    if a[i] % 2 == 0 :
        b.append(a[i])
        
b

[10, 12, 14, 16]

In [203]:
a  =  [40,11,12,13,14,15,16]

def even(i) :
    return i % 2 == 0


b = list(filter(even,a))
b

[40, 12, 14, 16]

In [204]:
a  =  [40,11,12,13,14,15,16]

b = list(filter(lambda p : p%2== 0,a))
b

[40, 12, 14, 16]

In [205]:
a = ["swapna","saraswati","abhi"]

b = list(filter(lambda i : i[0] != "a"   and  i[0] != "i"  and  i[0] != "o", a))
b

['swapna', 'saraswati']

In [206]:
a = {10,30,-10,0,30}
b = list(filter(lambda i : i >= 0 , a))
b

[0, 10, 30]

In [207]:
a = ["swapna","abhinav"]

In [208]:
# reduce 
from functools import reduce

a = [10,20,30,40,50]
b = 0
for i in a :
    b = b + i
    
b

150

In [209]:

c = [10,20,30,40,50]


def add(p,q) :
    return p + q
# ini = 100 
d = reduce(add,c)
d

150

In [210]:
c = [10,20,30,40,50]

mx = c[0]
for i in c :
    if i > mx :
        mx = i
mx

50

In [211]:
c = [10,770,30,40,50]
ini = int(c[0])
def maxx(p,q):
    if p > q :
        return p 
    else :
        return q

    
        
    
# ini = c[0]
d = reduce(maxx,c)
d

770

In [212]:
d = ["mlv","prasad","mentor"]
# d = ["mlv prasad","mentor"]

def con (p,q) :
    if p != "c001":
        return p + " c001" + q
    else :
        return p + q

e = reduce(con, d,"c001")
e

'c001mlv c001prasad c001mentor'

In [213]:
a = [10,29,32]

b = list(filter( lambda x : x < 15  , a))
b

[10]

In [214]:
d = ["mlv","prasad","mentor"]
e = reduce(lambda x,y : x + " " + y, d)
e

'mlv prasad mentor'

In [215]:
#map

a = [10,25,30,35,50]

# fil  = [10,30,50]

# reduce = one final ans 

#map - apply some function on all elememts


b = []
for i in a :
    b.append(i**2)
b



[100, 625, 900, 1225, 2500]

In [216]:
c = [10,25,30,35,50]
def sq(x) :
    return x**2
d = list(map(sq, c))
d

[100, 625, 900, 1225, 2500]

In [217]:
c = [10,25,30,35,50]

d = list(map(lambda i : i **2 , c))
d

[100, 625, 900, 1225, 2500]

In [218]:
a = ["swapna","sush","ghosh"]
b = list(filter(lambda x : x[0]=="s",a))
b

['swapna', 'sush']

In [219]:
a = ["swapna","sush","ghosh"]
b = list(map(lambda i : "student "+ i,a))
b

['student swapna', 'student sush', 'student ghosh']

In [220]:
a = ["swapna","prasad","ghosh"]
b = [100,200,300]


c = [  ( a[i] , b[i]) for i in range(len(a))]
c

[('swapna', 100), ('prasad', 200), ('ghosh', 300)]

In [221]:
for i in range(len(a) ) :
    print(a[i],b[i])
    

swapna 100
prasad 200
ghosh 300


In [222]:
for i in zip(a,b) :
    print(i,"--")

('swapna', 100) --
('prasad', 200) --
('ghosh', 300) --


In [223]:
for i,j in zip(a,b) :
    print(i,"--",j)

swapna -- 100
prasad -- 200
ghosh -- 300


In [224]:
a = ["swapna"]
b = [100,200,300]
c= [1,2]


c = list(zip(a,b,c))
c

[('swapna', 100, 1)]

In [225]:
a = "malayalam"
b = a[::-1]
b

if a == b :
    print("yes")
else :
    print("no")

yes


In [226]:
class BluePrint() :
    
    def __init__ (self,a ): # constructor
        self.b = a + 100
        self.designed = "mlv prasad"
        self.country  = "india"
        


    

    def color(self):
#         b = self.designed
        return f"home is designed by {self.designed} for  and is 100 ft and color "

    def interior(self):
        return "home is italian "
    
ghosh = BluePrint(100.5)
# int(ghosh)

In [227]:
# swapna = BluePrint()
# swapna.color()

In [228]:
a = 9
b = str(a)
b

'9'

In [229]:
class Student() :
    
    def __init__(self,name,age):
        self.studname = f"the student name is {name}"
        self.studage = f"the student age is {age}"
        self.courses= []
    
    def enroll(self, course= 0 ) :
        self.courses.append(course)
        
    def total_course(self):
        return len(self.courses)
    
    
    
joy =  Student("joyce","30")
joy.total_course()





0

In [230]:
sw = Student("swapna","35")
sw.courses

[]

In [231]:
joy.courses

# joy.enroll("sql")

[]

In [232]:
sw.enroll("sql")

In [233]:
joy.courses

[]

In [234]:
joy.enroll("python")

In [235]:
joy.courses

['python']

In [236]:
joy.total_course()

1

In [237]:
sw.courses

['sql']

In [238]:
sw.total_course()

1

In [239]:
class Vehicle :
    
    def __init__ (self,brand,model ):
        self.brand = brand
        self.model = model
        
    def info(self):
        return f"the owner brand is {self.brand}"
    
    
    
class Toyato(Vehicle):
    def __init__(self,brand,model,doors) : 
        super().__init__(brand,model)
        self.doors= doors
    def info(self):
        return f"{super().info()} and number of doors is {self.doors}"
    
swapna = Toyato("TYT","fortuner",6)

print(swapna.info())


the owner brand is TYT and number of doors is 6


In [240]:
def fibonaci ()  :
    a,b = 1,1
    while True :
        yield a 
        a,b = b, a+b # 2 3 
        
joy =  fibonaci()
for i in range(13) :
    print(next(joy))

1
1
2
3
5
8
13
21
34
55
89
144
233


In [241]:
#poly morphism

In [242]:
class Animal() :
    def speak(self) :
        pass
class Dog(Animal) :
    def speak(self) :
        return "doggy"
class Cat(Animal) :
    def speak( self) :
        return "catty"
    
def sound(Animal) :
    return    Animal.speak()

dog = Dog()
cat = Cat()

print(sound(cat))
print(sound(dog))

catty
doggy


In [243]:
class Student :
    def __init__(self, name, rno) :
        self.a = 10
        self.__name = name
        self._roll_no = rno
        
    def getname (self) :
        return self.__name
    def setname(self,name ) :
        if len(name) >= 3 :
            self.__name = name
        else :
            print("Name is too shot")
        
    def display(self) :
        print(self.__name)
        print(self._roll_no)
        
swapna = Student("swa",300)
swapna.display()
swapna.setname("ghosh")
swapna.display()


swa
300
ghosh
300


In [244]:
# swapna.__name
swapna.a

10

In [245]:
# ##### Write a Python program that accepts a sequence of c
# # omma-separated numbers from the user and generates a list and a tuple of those numbers.
# # Sample data : 3, 5, 7, 23
# ls = []
# for i in range(4):
#     a =int(input())
#     ls.append(a)
# print(f"the required answer is {ls} and {tuple(ls)}")

In [246]:
# Write a Python program to display the examination schedule. 
# (extract the date from exam_st_date).
# exam_st_date = (11, 12, 2014)
# Sample Output : The examination will start from : 11 / 12 / 2014

In [247]:
exam_st_date = (6, 5, 2023)
for i in range(1):
    print(f"The examination will start from : {exam_st_date[i] }/{ exam_st_date[i+1] }/ {exam_st_date[i+2]}")

The examination will start from : 6/5/ 2023


In [248]:
a = 10
b = 20

print("score of a is",a, "score of b is ",b)
print(f"score of a is {a} score of b is {b}")

score of a is 10 score of b is  20
score of a is 10 score of b is 20


In [249]:
# # Sample data : 3, 5, 7, 23
# ls = []
# for i in range(1):
#     a =input()
#     ls.append(a)
# print(f"the required answer is {ls} and {tuple(ls)}")

In [250]:
a = "my name is mlv prasad and is am a good boy"
b = a.split("is")
b

['my name ', ' mlv prasad and ', ' am a good boy']

In [251]:
for i in range(5):
    print("  "*(2*(4-i)),end="")
    print("* "* ( (2*i)+1) )
    

                * 
            * * * 
        * * * * * 
    * * * * * * * 
* * * * * * * * * 


In [252]:
#                 * 
#             * * * 
#         * * * * * 
#     * * * * * * * 
# * * * * * * * * * 

from abc import ABC , abstractmethod

class mlv(ABC):
    @abstractmethod
    def marks(self) :
        pass
#     @abstractmethod 
#     def classes(self) :
#         pass
    
class Mentor(mlv) :
    def __init__(self,teach):
        self.teach = teach
        
    def marks(self) :
        return 9 * self.teach
    
    
class Instructor(mlv) :
    def __init__(self,cltime, months) :
        self.cltime = cltime
        self.month = months
        
    def marks(self) :
        return self.cltime * self.month
c1 = Mentor(5)
c2 = Instructor(4,3)
shapes = [c1, c2]
for c3 in shapes :
    print(c3.marks())

45
12


In [253]:
a = "english"

b = "hsilgne"


c = "malayalam"
d = "malayalam"

# palindrome

In [254]:
a = ["a","b","c"]
b = a[::-1]
b

['c', 'b', 'a']

In [255]:
c = "prasad"
c[::-1]

'dasarp'

In [256]:


# a  = input()
# b = a[::-1]


# if a == b :
#     print("palindrome")
# else :
#     print("not a palindrome")

In [257]:
a = "mlv prasad is a mentor"

# b = "mentor a is prasad mlv"
b = a.split()
c = b[::-1]
c

d =  " ".join(c)
d

'mentor a is prasad mlv'

In [258]:
a = "mlv prasad is a mentor"

# b = "mentor a is prasad mlv"
b = a.split()
b 

['mlv', 'prasad', 'is', 'a', 'mentor']

In [259]:
a = "swapna"
print("the student name is ", a,"and she is a  good student")

the student name is  swapna and she is a  good student


In [260]:
print(f"the student name is  {a}  and she is a  good student")

the student name is  swapna  and she is a  good student


In [261]:
txt = "the student name is  {}  and she is a  good student"
print(txt.format(a))

the student name is  swapna  and she is a  good student


In [262]:
# 9. Write a Python program to display the examination schedule. (extract the date from exam_st_date).
# exam_st_date = (11, 12, 2014)
# Sample Output : The examination will start from : 11 / 12 / 2014


# 10. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.
# Sample value of n is 5
# Expected Result : 615

# 11. Write a Python program to print the documents (syntax, description etc.) of Python built-in function(s).
# Sample function : abs()
# Expected Result :
# abs(number) -> number
# Return the absolute value of the argument.

In [263]:
exam_st_date = (15, 3, 2022)
a, b ,c = exam_st_date 
print(f"Sample Output : The examination will start from : {a} / {b} / {c}")

Sample Output : The examination will start from : 15 / 3 / 2022


In [264]:
# 10. Write a Python program that accepts an integer (n) and computes the value of n+nn+nnn.
# Sample value of n is 5
# Expected Result : 615


# 7 

# 7 + 77 + 777

n = 7 
sum = 0
for i in range(3):
    a  = str(7)*(i+1)
    print(a)
    sum = sum + int(a)
    
sum    

7
77
777


861

In [265]:
# 7 + 77 + 777

In [266]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [267]:
help(str)

Help on class str in module builtins:

class str(object)
 |  str(object='') -> str
 |  str(bytes_or_buffer[, encoding[, errors]]) -> str
 |  
 |  Create a new string object from the given object. If encoding or
 |  errors is specified, then the object must expose a data buffer
 |  that will be decoded using the given encoding and error handler.
 |  Otherwise, returns the result of object.__str__() (if defined)
 |  or repr(object).
 |  encoding defaults to sys.getdefaultencoding().
 |  errors defaults to 'strict'.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __format__(self, format_spec, /)
 |      Return a formatted version of the string as described by format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  

In [268]:
help(int)

Help on class int in module builtins:

class int(object)
 |  int([x]) -> integer
 |  int(x, base=10) -> integer
 |  
 |  Convert a number or string to an integer, or return 0 if no arguments
 |  are given.  If x is a number, return x.__int__().  For floating point
 |  numbers, this truncates towards zero.
 |  
 |  If x is not a number or if base is given, then x must be a string,
 |  bytes, or bytearray instance representing an integer literal in the
 |  given base.  The literal can be preceded by '+' or '-' and be surrounded
 |  by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
 |  Base 0 means to interpret the base from the string as an integer literal.
 |  >>> int('0b100', base=0)
 |  4
 |  
 |  Built-in subclasses:
 |      bool
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __and__(self, value, /)
 |      Return self&value.
 |  
 |  __bool__(self, /)
 |      True if 

In [269]:
a = -9

b = 10

print(abs(a),abs(b))

9 10


In [270]:
dt = {"beautiful": "which is glorious",
     "great": " to do some extraordinary",
     "maths": "study of numericals"}
dt.keys()

dict_keys(['beautiful', 'great', 'maths'])

In [271]:
dt.values()

dict_values(['which is glorious', ' to do some extraordinary', 'study of numericals'])

In [272]:
dt.items()

dict_items([('beautiful', 'which is glorious'), ('great', ' to do some extraordinary'), ('maths', 'study of numericals')])

In [273]:
dt["maths"].split()[0]

'study'

In [274]:
p= ["a","b","c"]
q = ["ddddd","eeeee","fffff"]

ans = {  p[i] : q[i]    for i in range(len(p))}
ans

{'a': 'ddddd', 'b': 'eeeee', 'c': 'fffff'}

In [275]:
car = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

car.popitem()

print(car)

{'brand': 'Ford', 'model': 'Mustang'}


In [276]:
a = ["suhs","mlv","prasad"]
a.pop()

'prasad'

In [277]:
# numpy

# numerical python


In [278]:
a = [10,20,30]
a

[10, 20, 30]

In [279]:
import numpy as np


b = np.array([10,20,30])
b

array([10, 20, 30])

In [280]:
b[0]

10

In [281]:
b[-1]

30

In [282]:
b[0:2]

array([10, 20])

In [283]:
c = [10,20,30]

d = np.array(c)
d

array([10, 20, 30])

In [284]:
e = np.zeros((5,5))  
e

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [285]:
f = np.ones((2,6))
f

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [286]:
import numpy as np
g = np.full((5,8),22)
g

array([[22, 22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22, 22],
       [22, 22, 22, 22, 22, 22, 22, 22]])

In [287]:
# range(5) = [0,1,2,3,4]

h = np.arange(2,5)
h

array([2, 3, 4])

In [288]:
i = np.linspace(2,12,6).astype("int")
i

array([ 2,  4,  6,  8, 10, 12])

In [289]:
a = np.random.rand(5,5)* 100 # 0 - 1
a

array([[54.07340637,  5.45156893,  4.90043227, 12.83300527, 78.39046492],
       [53.41302195, 83.13895747, 93.32988998, 44.12856357, 20.52399279],
       [63.80317886, 11.03016382, 45.49532181, 49.35787366, 15.88738774],
       [31.88998434, 83.34213948, 34.39728062, 52.01039571, 82.67636388],
       [99.48815089, 11.33027341, 73.07753692, 64.28254959, 15.56748302]])

In [290]:
b = np.random.randint(10,20,(2,3))
b

array([[16, 14, 16],
       [17, 17, 15]])

In [291]:
a = [[1,2,3],[4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [292]:
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [293]:
a = np.zeros((10,10))
b = a[:5,:]

In [294]:
b.shape[1]

10

In [295]:
a = [[0,0,0,0],[0,0,0,0]]
b = np.array(a)
b.reshape((1,8))

array([[0, 0, 0, 0, 0, 0, 0, 0]])

In [296]:
a = [0,0,0,0]
b = np.array(a)
b= b[:,np.newaxis]
b

array([[0],
       [0],
       [0],
       [0]])

In [297]:
b.dtype

dtype('int64')

In [298]:
a = [0,1,0,0]
b = np.array(a,dtype= float)
b

array([0., 1., 0., 0.])

In [299]:
a = [100,120,115,140]
b = [10,10,10,10]
a + b

[100, 120, 115, 140, 10, 10, 10, 10]

In [300]:
a = np.array([100,120,115,140])
b = np.array([1.1,1.1,1.1,1.1])
a * b

array([110. , 132. , 126.5, 154. ])

In [301]:
a = np.array([100,120,115,140])
b = 1.1
a * b

array([110. , 132. , 126.5, 154. ])

In [302]:
a = np.array([100,120,115,140])

np.sum(a)

475

In [303]:
np.max(a)

140

In [304]:
np.min(a)

100

In [305]:
np.var(a)

204.6875

In [306]:
np.std(a)

14.306903927824496

In [307]:
np.sqrt(a)

array([10.        , 10.95445115, 10.72380529, 11.83215957])

In [308]:
np.cos(a)

array([ 0.86231887,  0.81418097, -0.32580981, -0.19781357])

In [309]:
np.exp(a)

array([2.68811714e+43, 1.30418088e+52, 8.78750164e+49, 6.32743171e+60])

In [310]:
np.mean(a)

118.75

In [311]:
np.median(a)

117.5

In [312]:
np.sort(a)

array([100, 115, 120, 140])

In [313]:
# np.sort(a,reverse = True)

In [314]:
# help(np.sort(a))

In [315]:
np.sort(a)[::-1]

array([140, 120, 115, 100])

In [316]:
a = [10,20,15]
sorted(a,reverse = True)


[20, 15, 10]

In [317]:
a = [10,20,30,15]
print(a.sort())


None


In [318]:
sorted(a)

[10, 15, 20, 30]

In [319]:
b = [10,9]
b.sort()
b

[9, 10]

In [320]:
# sort  inplace
# soerted new list


# np.sort()  new list 

In [321]:
import numpy as np

a = np.array([90,85,60,79,90])


np.where ( a > 80)


(array([0, 1, 4]),)

In [322]:
#seed
np.random.seed(80)
a = np.random.rand(2,3)
a

array([[0.52191572, 0.69940637, 0.26986897],
       [0.67448187, 0.90807208, 0.6851502 ]])

In [323]:
a = np.random.rand(2,3)
a

array([[0.21165334, 0.31726607, 0.2672994 ],
       [0.12050632, 0.9968569 , 0.08043969]])

In [324]:
np.random.seed(80)
a = np.random.rand(2,3)
a

array([[0.52191572, 0.69940637, 0.26986897],
       [0.67448187, 0.90807208, 0.6851502 ]])

In [325]:
np.linspace(20,60,6)

array([20., 28., 36., 44., 52., 60.])

In [326]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [327]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [328]:
c  = np.vstack((a,b))
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [329]:
# d  = np.hstack((a,b))
# e = np.

In [330]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [331]:
# np.genfromtxt("a.csv")

In [332]:
np.save("parth.npy",b)

In [333]:
np.load("parth.npy")

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [334]:
a = np.ones((8,240))
a

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [335]:
a.reshape(1,-1)


array([[1., 1., 1., ..., 1., 1., 1.]])

In [336]:
a.flatten()

array([1., 1., 1., ..., 1., 1., 1.])

In [337]:
a = np.zeros((4,4))

In [338]:
a = a.reshape(2,8)
a.shape

(2, 8)

In [339]:
a = a.reshape(2,-1)
a.shape

(2, 8)

In [340]:
c = np.array([9,8,6])
b = np.append(c,[88,99])
b

array([ 9,  8,  6, 88, 99])

In [341]:
c = np.array([9,8,6])
b = np.insert(c,1,[88,99])
b

array([ 9, 88, 99,  8,  6])

In [342]:
c = np.array([9,8,6])
b = np.delete(c,2)
b

array([9, 8])

In [343]:
a= np.ones((4,4))
a = a.reshape((8,-1))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [344]:
a= np.ones((4,4))
a.resize((8,2))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [345]:
a = np.array([True, True, True, False])
b = np.array([False, True,False, False])

c = np.logical_and(a,b)
c

array([False,  True, False, False])

In [346]:
a = np.array([True, True, True, False])
b = np.array([False, True,False, False])

c = np.logical_or(a,b)
c

array([ True,  True,  True, False])

In [347]:
a = np.array([True, True, True, False])
b = np.logical_not(a)
b

array([False, False, False,  True])

In [348]:
a = np.array([10,20,30])
a[np.where ( a > 15)]


array([20, 30])

In [349]:
import numpy as np

In [350]:
a = np.array([True, True, True, False])
b = np.array([False, True,False, False])

c =  a & b
c

array([False,  True, False, False])

In [351]:
a = np.array([True, True, True, False])
b = np.array([False, True,False, False])

c =  a | b # or 
c

array([ True,  True,  True, False])

In [352]:
a = np.array([True, True, True, False])
c = ~a
c

array([False, False, False,  True])

In [353]:
a = np.ones((5,5))
b = np.full((5,5), 3)
c = np.dot(a,b)
c

array([[15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.],
       [15., 15., 15., 15., 15.]])

In [354]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [355]:
b = np.transpose(a)
b

array([[1, 3],
       [2, 4]])

In [356]:
a = np.random.normal(0,1,(3,3))
a

array([[-0.66136743, -1.04361074, -0.58114897],
       [-0.356353  ,  0.29407381, -1.79697064],
       [-0.38949016,  0.44914091, -0.47389926]])

In [357]:
b = np.random.uniform(50,55,(3,3))
b

array([[54.04820621, 50.05997631, 53.34034706],
       [51.45262098, 51.61359903, 52.08854957],
       [52.43197998, 54.7133926 , 53.66073862]])

In [358]:
np.random.seed(10)

c = np.random.randint(50,55,(3,3))
c

array([[51, 54, 50],
       [51, 53, 54],
       [51, 50, 51]])

In [359]:
np.random.seed(10)

c = np.random.randint(50,55,(3,3))
c

array([[51, 54, 50],
       [51, 53, 54],
       [51, 50, 51]])

In [360]:
# c = np.random.randint(50,55,(1,3))
c = np.array([9,8,7,6,5])

d = np.random.choice( c,size =  10, replace = True ,p=[0.32, 0.02, 0.02, 0.04, 0.6])
d
# d

array([5, 9, 9, 9, 5, 5, 8, 5, 9, 9])

In [361]:
# c = [9,8,6,5]
# np.random.choice(c, 3, p=[0.5, 0.1, 0.1, 0.3])

In [362]:
# 9,8,7,6,5

# 6

# 9,8,7,5

In [363]:
a = np.array([[1,2],[3,4]])
a
    

array([[1, 2],
       [3, 4]])

In [364]:
np.zeros(a.shape)

array([[0., 0.],
       [0., 0.]])

In [365]:
np.zeros_like(a)

array([[0, 0],
       [0, 0]])

In [366]:
c = np.ones_like(a)

In [367]:
c = np.ones_like(a)
d = c + 2
d

array([[3, 3],
       [3, 3]])

In [368]:
# help(int)

In [369]:
import numpy as np

arr1= np.array([4, 11, 53, 2, 9, ])
arr1.dtype

dtype('int64')

In [370]:
arr2 = np.array([[2, 7 , 11], [4, 8 , 2]],
dtype= float)
arr2.dtype
arr2

array([[ 2.,  7., 11.],
       [ 4.,  8.,  2.]])

In [371]:
import numpy as np
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


# pandas

In [372]:
!pip install pandas

In [373]:
import pandas as pd


print(pd.__version__)

2.0.3


In [374]:
df = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
0                    KPCB, Sherpalo Ventures, SoftBank  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  
2             Accel, Sequoia Capital, General Atlantic  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  
..                                                 ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal  

[102 rows x 8 columns]

In [375]:
af = pd.DataFrame({ "sno"  :    [1,2,3],
                   "names"  : ["mlv","abhi","joy"],
                   "marks" : [10,20,30]
    
                
                   })


af

sno names  marks
0    1   mlv     10
1    2  abhi     20
2    3   joy     30

In [376]:
# select * from af

af

sno names  marks
0    1   mlv     10
1    2  abhi     20
2    3   joy     30

In [377]:
# select names, marks from af


af[["names","marks"]]

names  marks
0   mlv     10
1  abhi     20
2   joy     30

In [378]:
# desc af


af.columns

Index(['sno', 'names', 'marks'], dtype='object')

In [379]:
af.shape

(3, 3)

In [380]:
af.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   sno     3 non-null      int64 
 1   names   3 non-null      object
 2   marks   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [381]:
# str - object - category 
af.describe()

sno  marks
count  3.0    3.0
mean   2.0   20.0
std    1.0   10.0
min    1.0   10.0
25%    1.5   15.0
50%    2.0   20.0
75%    2.5   25.0
max    3.0   30.0

In [382]:
df.shape

(102, 8)

In [383]:
# select * from af limit 10

df.head(10)

No.     Company                       Sector  Entry Valuation^^ ($B)  \
0    1      InMobi          Adtech - Mobile Ads                     1.0   
1    2   Flipkart^                   E-Commerce                     1.0   
2    3    Mu Sigma             SaaS - Analytics                     1.0   
3    4   Snapdeal*                   E-Commerce                     1.8   
4    5      PayTM^  Fintech - Payments & Wallet                     1.7   
5    6    Ola Cabs   Mobility - Ride Aggregator                     1.6   
6    7      Quikr*    Marketplace - Classifieds                     1.0   
7    8     Zomato^                     Foodtech                     1.0   
8    9  ShopClues*                   E-Commerce                     1.1   
9   10       Hike*     Social Media - Messaging                     1.4   

   Valuation ($B)     Entry             Location  \
0             1.0  Sep/2011  Bangalore/Singapore   
1            37.6  Feb/2012  Bangalore/Singapore   
2             1.5  Feb/2013    Bangalore/Chicago   
3             2.4  Oct/2014                Delhi   
4            16.0  Feb/2015                Noida   
5             7.3  Mar/2015            Bangalore   
6             1.5  Apr/2015            Bangalore   
7             5.4  Sep/2015              Gurgaon   
8             1.1  Jan/2016              Gurgaon   
9             1.4  Aug/2016                Delhi   

                                    Select Investors  
0                  KPCB, Sherpalo Ventures, SoftBank  
1    Accel, Tiger Global, Naspers, SoftBank, Tencent  
2           Accel, Sequoia Capital, General Atlantic  
3  Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4  Saama Capital, Elevation Capital, Alibaba, Ber...  
5  Tiger Global, Matrix Partners, Steadview, Soft...  
6  Matrix Partners, Omidyar Network, Norwest, Kin...  
7  Info Edge, Sequoia Capital, Vy Capital, Alibab...  
8  Nexus Ventures, Helion Ventures, Beenos, Tiger...  
9                     Tiger Global, Tencent, Foxconn

In [384]:
df.tail(10)

No.                      Company                                  Sector  \
92    93             Amagi Media Labs              SaaS - Local Ads Targeting   
93    94     Oxyzo Financial Services     Fintech - Marketplace - SME Lending   
94    95                    Games24x7                                  Gaming   
95    96  Open Financial Technologies                      Fintech - Neo Bank   
96    97                PhysicsWallah                                  Edtech   
97    98                      Purplle  E-Commerce - Personal Care & Cosmetics   
98    99                  Leadsquared                              SaaS - CRM   
99   100                      OneCard                  Fintech - Credit Cards   
100  101                   Shiprocket         Aggregator - Logistics Services   
101  102           Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry   Location  \
92                     1.00            1.00  Mar/2022  Bangalore   
93                     1.00            1.00  Mar/2022    Gurgaon   
94                     2.50            2.50  Mar/2022     Mumbai   
95                     1.00            1.00  May/2022  Bangalore   
96                     1.10            1.10  Jun/2022      Noida   
97                     1.10            1.10  Jun/2022     Mumbai   
98                     1.00            1.00  Jun/2022  Bangalore   
99                     1.30            1.30  Jul/2022       Pune   
100                    1.23            1.23  Aug/2022      Delhi   
101                    1.53            1.53  Sep/2022        Goa   

                                      Select Investors  
92   Avataar Venture Partners, PremjiInvest, Accel ...  
93   Alpha Wave Global, Matrix Partners India, Tige...  
94   Tiger Global, Malabar Investments,  The Raine ...  
95   3ONE4 Capital, Tiger Global, Temasek, Speedinvest  
96                            GSV Ventures, WestBridge  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal

In [385]:
# a = [1,2,34,5]
# a[1:3]

In [386]:
df.iloc[2:10,5:7]

Entry           Location
2  Feb/2013  Bangalore/Chicago
3  Oct/2014              Delhi
4  Feb/2015              Noida
5  Mar/2015          Bangalore
6  Apr/2015          Bangalore
7  Sep/2015            Gurgaon
8  Jan/2016            Gurgaon
9  Aug/2016              Delhi

In [387]:
df.loc[2:9,["Entry","Location"]]

Entry           Location
2  Feb/2013  Bangalore/Chicago
3  Oct/2014              Delhi
4  Feb/2015              Noida
5  Mar/2015          Bangalore
6  Apr/2015          Bangalore
7  Sep/2015            Gurgaon
8  Jan/2016            Gurgaon
9  Aug/2016              Delhi

In [388]:
# iloc  


# select * from df 
# where location = "delhi" and no < 50


df[  (df["Location"] == "Delhi" )   &   ( df["No."]  < 50)]

No.    Company                    Sector  Entry Valuation^^ ($B)  \
3     4  Snapdeal*                E-Commerce                     1.8   
9    10      Hike*  Social Media - Messaging                     1.4   
26   27   Lenskart      E-Commerce - Eyewear                     1.1   

    Valuation ($B)     Entry Location  \
3              2.4  Oct/2014    Delhi   
9              1.4  Aug/2016    Delhi   
26             4.5  Sep/2019    Delhi   

                                     Select Investors  
3   Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
9                      Tiger Global, Tencent, Foxconn  
26  SoftBank, Kedaara Capital, TPG, Chiratae Ventu...

In [389]:


# select * from df 
# where location = "delhi" or no < 50
df[  (df["Location"] == "Delhi" )  |  ( df["No."]  < 50)]




No.                      Company  \
0      1                       InMobi   
1      2                    Flipkart^   
2      3                     Mu Sigma   
3      4                    Snapdeal*   
4      5                       PayTM^   
5      6                     Ola Cabs   
6      7                       Quikr*   
7      8                      Zomato^   
8      9                   ShopClues*   
9     10                        Hike*   
10    11                        BYJUS   
11    12                  PayTM Mall*   
12    13                       Swiggy   
13    14                PolicyBazaar^   
14    15                  Freshworks^   
15    16                    OYO Rooms   
16    17                        Udaan   
17    18                     BillDesk   
18    19                   Delhivery^   
19    20                       Rivigo   
20    21                    BigBasket   
21    22                      Dream11   
22    23               Druva Software   
23    24                      Icertis   
24    25                   CitiusTech   
25    26                 Ola Electric   
26    27                     Lenskart   
27    28                    Pine Labs   
28    29                       Nykaa^   
29    30                      Postman   
30    31                    Unacademy   
31    32                     RazorPay   
32    33                       Cars24   
33    34                     PhonePe^   
34    35                       Zenoti   
35    36                    Dailyhunt   
36    37                Glance InMobi   
37    38                        Digit   
38    39                   Innovaccer   
39    40                 Infra.Market   
40    41  Five Star Business Finance^   
41    42                     FirstCry   
42    43                       Meesho   
43    44                         CRED   
44    45                    PharmEasy   
45    46                        Groww   
46    47                    ShareChat   
47    48                      Gupshup   
48    49                    ChargeBee   
49    50                Urban Company   
56    57                     BharatPe   
80    81                   GlobalBees   
100  101                   Shiprocket   

                                       Sector  Entry Valuation^^ ($B)  \
0                         Adtech - Mobile Ads                    1.00   
1                                  E-Commerce                    1.00   
2                            SaaS - Analytics                    1.00   
3                                  E-Commerce                    1.80   
4                 Fintech - Payments & Wallet                    1.70   
5                  Mobility - Ride Aggregator                    1.60   
6                   Marketplace - Classifieds                    1.00   
7                                    Foodtech                    1.00   
8                                  E-Commerce                    1.10   
9                    Social Media - Messaging                    1.40   
10                                     Edtech                    1.00   
11                                 E-Commerce                    1.90   
12                                   Foodtech                    1.40   
13                        Fintech - Insurance                    1.00   
14                                 SaaS - CRM                    1.50   
15                   Proptech - Hotel Booking                    4.90   
16                             B2B E-Commerce                    1.00   
17                     Fintech - B2B Payments                    1.60   
18                         Logistics Services                    1.60   
19                Logistics Services - Trucks                    1.10   
20                     E-Commerce - Groceries                    1.10   
21                                     Gaming                    1.00   
22                     SaaS - Data Management                    1.00   
23                 SaaS - Contract Man

In [390]:
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
0                    KPCB, Sherpalo Ventures, SoftBank  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  
2             Accel, Sequoia Capital, General Atlantic  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  
..                                                 ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal  

[102 rows x 8 columns]

In [391]:


# select * from df 
# where location = "Delhi" or location = "Pune"
# where location in ("delhi,Pune")

df[df["Location"].isin(["Delhi","Pune"])]

No.               Company                           Sector  \
3      4             Snapdeal*                       E-Commerce   
9     10                 Hike*         Social Media - Messaging   
26    27              Lenskart             E-Commerce - Eyewear   
41    42              FirstCry  E-Commerce - Baby Care Products   
49    50         Urban Company  Marketplace - Handyman Services   
56    57              BharatPe               Fintech - Payments   
80    81            GlobalBees     Aggregator - Consumer Brands   
86    87            ElasticRun               Logistics Services   
88    89  XpressBees Logistics               Logistics Services   
99   100               OneCard           Fintech - Credit Cards   
100  101            Shiprocket  Aggregator - Logistics Services   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry Location  \
3                      1.80            2.40  Oct/2014    Delhi   
9                      1.40            1.40  Aug/2016    Delhi   
26                     1.10            4.50  Sep/2019    Delhi   
41                     1.70            1.70  Mar/2021     Pune   
49                     2.10            2.10  Apr/2021    Delhi   
56                     2.80            2.80  Aug/2021    Delhi   
80                     1.10            1.10  Dec/2021    Delhi   
86                     1.40            1.40  Feb/2022     Pune   
88                     1.20            1.20  Feb/2022     Pune   
99                     1.30            1.30  Jul/2022     Pune   
100                    1.23            1.23  Aug/2022    Delhi   

                                      Select Investors  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
9                       Tiger Global, Tencent, Foxconn  
26   SoftBank, Kedaara Capital, TPG, Chiratae Ventu...  
41   Chiratae Ventures, Elevation Capital, Vertex, ...  
49   Tiger Global, Steadview Capital, Accel India, ...  
56   Beenext, Sequoia Capital India, Tiger Global, ...  
80   PremjiInvest, SoftBank Corp, TPG Capital, Stea...  
86   SoftBank, Goldman Sachs, Prosus Ventures, Kala...  
88   InvestCorp Group, Norwest, Gaja Capital, TPG G...  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...

In [392]:

# select * from df 
# where Sector like "%services%"
df[df["Sector"].str.contains("Services")]

No.               Company                                  Sector  \
18    19            Delhivery^                      Logistics Services   
19    20                Rivigo             Logistics Services - Trucks   
24    25            CitiusTech                IT Services - Healthcare   
49    50         Urban Company         Marketplace - Handyman Services   
53    54             BlackBuck                      Logistics Services   
62    63               Zetwerk    Marketplace - Manufacturing Services   
78    79          Pristyn Care  Healthtech - Elective Surgery Services   
86    87            ElasticRun                      Logistics Services   
88    89  XpressBees Logistics                      Logistics Services   
100  101            Shiprocket         Aggregator - Logistics Services   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry          Location  \
18                     1.60            3.00  Jan/2019           Gurgaon   
19                     1.10            1.10  Feb/2019           Gurgaon   
24                     1.10            1.10  Jul/2019  Mumbai/Princeton   
49                     2.10            2.10  Apr/2021             Delhi   
53                     1.00            1.00  Jul/2021         Bangalore   
62                     1.00            2.50  Aug/2021         Bangalore   
78                     1.40            1.40  Dec/2021           Gurgaon   
86                     1.40            1.40  Feb/2022              Pune   
88                     1.20            1.20  Feb/2022              Pune   
100                    1.23            1.23  Aug/2022             Delhi   

                                      Select Investors  
18   Nexus Ventures, Multiples PE, Tiger Global, Ca...  
19                   Elevation Capital, Warburg Pincus  
24                       General Atlantic, Baring Asia  
49   Tiger Global, Steadview Capital, Accel India, ...  
53   Accel India, Sequoia Capital India, Sands Capi...  
62   Kae Capital, Sequoia Capital India, Accel Indi...  
78   Tiger Global, Sequoia Capital India, Hummingbi...  
86   SoftBank, Goldman Sachs, Prosus Ventures, Kala...  
88   InvestCorp Group, Norwest, Gaja Capital, TPG G...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...

In [393]:

# select * from df 
# where Sector like "%services"
df[df["Sector"].str.endswith("Services")]

No.               Company                                  Sector  \
18    19            Delhivery^                      Logistics Services   
49    50         Urban Company         Marketplace - Handyman Services   
53    54             BlackBuck                      Logistics Services   
62    63               Zetwerk    Marketplace - Manufacturing Services   
78    79          Pristyn Care  Healthtech - Elective Surgery Services   
86    87            ElasticRun                      Logistics Services   
88    89  XpressBees Logistics                      Logistics Services   
100  101            Shiprocket         Aggregator - Logistics Services   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry   Location  \
18                     1.60            3.00  Jan/2019    Gurgaon   
49                     2.10            2.10  Apr/2021      Delhi   
53                     1.00            1.00  Jul/2021  Bangalore   
62                     1.00            2.50  Aug/2021  Bangalore   
78                     1.40            1.40  Dec/2021    Gurgaon   
86                     1.40            1.40  Feb/2022       Pune   
88                     1.20            1.20  Feb/2022       Pune   
100                    1.23            1.23  Aug/2022      Delhi   

                                      Select Investors  
18   Nexus Ventures, Multiples PE, Tiger Global, Ca...  
49   Tiger Global, Steadview Capital, Accel India, ...  
53   Accel India, Sequoia Capital India, Sands Capi...  
62   Kae Capital, Sequoia Capital India, Accel Indi...  
78   Tiger Global, Sequoia Capital India, Hummingbi...  
86   SoftBank, Goldman Sachs, Prosus Ventures, Kala...  
88   InvestCorp Group, Norwest, Gaja Capital, TPG G...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...

In [394]:
df[df["Sector"].str.startswith("Services")]

Empty DataFrame
Columns: [No., Company, Sector, Entry Valuation^^ ($B), Valuation ($B), Entry, Location, Select Investors]
Index: []

In [395]:
# select * from fd order by Location desc, sector asc
df.sort_values(["Location","Sector"], ascending = [False,True])

No.           Company                                   Sector  \
39   40      Infra.Market  B2B E-Commerce - Construction Materials   
22   23    Druva Software                   SaaS - Data Management   
23   24           Icertis               SaaS - Contract Management   
41   42          FirstCry          E-Commerce - Baby Care Products   
99  100           OneCard                   Fintech - Credit Cards   
..  ...               ...                                      ...   
98   99       Leadsquared                               SaaS - CRM   
92   93  Amagi Media Labs               SaaS - Local Ads Targeting   
90   91            Hasura                 SaaS - Programming Tools   
46   47         ShareChat                             Social Media   
85   86           Polygon              Web3 Infrastructure - Dapps   

    Entry Valuation^^ ($B)  Valuation ($B)     Entry        Location  \
39                     1.0             2.5  Feb/2021           Thane   
22                     1.0             2.0  Jun/2019  Pune/Sunnyvale   
23                     1.0             5.0  Jul/2019   Pune/Bellevue   
41                     1.7             1.7  Mar/2021            Pune   
99                     1.3             1.3  Jul/2022            Pune   
..                     ...             ...       ...             ...   
98                     1.0             1.0  Jun/2022       Bangalore   
92                     1.0             1.0  Mar/2022       Bangalore   
90                     1.0             1.0  Feb/2022       Bangalore   
46                     2.1             4.9  Apr/2021       Bangalore   
85                    10.0            10.0  Feb/2022       Bangalore   

                                     Select Investors  
39  Accel India, Nexus Venture Partners, Tiger Glo...  
22        WestBridge, Nexus Ventures, Sequoia Capital  
23               Eight Roads, B Capital, PremjiInvest  
41  Chiratae Ventures, Elevation Capital, Vertex, ...  
99  QED Investors, Matrix Partners India, Sequoia ...  
..                                                ...  
98        Stakeboat Capital, Gaja Capital, WestBridge  
92  Avataar Venture Partners, PremjiInvest, Accel ...  
90  Lightspeed Ventures, Nexus Venture Partners, V...  
46  India Quotient, Elevation Capital, Lightspeed ...  
85  Coinbase Ventures, Sequoia Capital India, Tige...  

[102 rows x 8 columns]

In [396]:
# select val + 2  as joyce from af
df["aa"] = df["Valuation ($B)"].apply(lambda x : x * 2 + 10)
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors     aa  
0                    KPCB, Sherpalo Ventures, SoftBank  12.00  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  85.20  
2             Accel, Sequoia Capital, General Atlantic  13.00  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  14.80  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  42.00  
..                                                 ...    ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  12.20  
98         Stakeboat Capital, Gaja Capital, WestBridge  12.00  
99   QED Investors, Matrix Partners India, Sequoia ...  12.60  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  12.46  
101                             Temasek, Motilal Oswal  13.06  

[102 rows x 9 columns]

In [397]:
df.columns

Index(['No.', 'Company', 'Sector', 'Entry Valuation^^ ($B)', 'Valuation ($B)',
       'Entry', 'Location', 'Select Investors', 'aa'],
      dtype='object')

In [398]:
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors     aa  
0                    KPCB, Sherpalo Ventures, SoftBank  12.00  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  85.20  
2             Accel, Sequoia Capital, General Atlantic  13.00  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  14.80  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  42.00  
..                                                 ...    ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  12.20  
98         Stakeboat Capital, Gaja Capital, WestBridge  12.00  
99   QED Investors, Matrix Partners India, Sequoia ...  12.60  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  12.46  
101                             Temasek, Motilal Oswal  13.06  

[102 rows x 9 columns]

In [399]:
df.drop("aa",axis = 1,inplace = True)

In [400]:
df

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
0                    KPCB, Sherpalo Ventures, SoftBank  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  
2             Accel, Sequoia Capital, General Atlantic  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  
..                                                 ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal  

[102 rows x 8 columns]

In [401]:
# select count(*) from af where entry is null

df.isnull().sum().sum()

0

In [402]:
print(int(True))

1


In [403]:
af

sno names  marks
0    1   mlv     10
1    2  abhi     20
2    3   joy     30

In [404]:
af = pd.DataFrame({ "sno"  :    [1,1,3],
                   "names"  : ["abhi","abhi","joy"],
                   "marks" : [10,10,None]
    
                
                   })


af

sno names  marks
0    1  abhi   10.0
1    1  abhi   10.0
2    3   joy    NaN

In [405]:
af.isnull().sum().sum()

1

In [406]:
af["names"].value_counts()

names
abhi    2
joy     1
Name: count, dtype: int64

In [407]:
af["names"].unique()

array(['abhi', 'joy'], dtype=object)

In [408]:
af["names"].nunique()

2

In [409]:
af

sno names  marks
0    1  abhi   10.0
1    1  abhi   10.0
2    3   joy    NaN

In [410]:
af.drop_duplicates()

sno names  marks
0    1  abhi   10.0
2    3   joy    NaN

In [411]:
af

sno names  marks
0    1  abhi   10.0
1    1  abhi   10.0
2    3   joy    NaN

In [412]:
af.drop_duplicates(inplace = True)
af

sno names  marks
0    1  abhi   10.0
2    3   joy    NaN

In [413]:
af = pd.DataFrame({ "sno"  :    [1,1,3],
                   "names"  : ["abhi","abhi","joy"],
                   "marks" : [10,10,20]
    
                
                   })




In [414]:
af.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   sno     3 non-null      int64 
 1   names   3 non-null      object
 2   marks   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 200.0+ bytes


In [415]:
af["sno"] = af["sno"].astype("float")
af.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sno     3 non-null      float64
 1   names   3 non-null      object 
 2   marks   3 non-null      int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes


In [416]:
af = af.astype({"sno":"float","marks" : "int" })
af.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   sno     3 non-null      float64
 1   names   3 non-null      object 
 2   marks   3 non-null      int64  
dtypes: float64(1), int64(1), object(1)
memory usage: 200.0+ bytes


In [417]:
af["marks" ] = (af["marks"] - af["marks"].mean())/af["marks"].std()
af

sno names     marks
0  1.0  abhi -0.577350
1  1.0  abhi -0.577350
2  3.0   joy  1.154701

In [418]:
import pandas as pd

data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-01'],
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Product': ['Apple', 'Orange', 'Apple', 'Orange', 'Apple'],
    'Sales': [100, 150, 200, 120, 180]
}

df = pd.DataFrame(data)
df


Date Region Product  Sales
0  2023-01-01   East   Apple    100
1  2023-01-01   West  Orange    150
2  2023-01-02   East   Apple    200
3  2023-01-02   West  Orange    120
4  2023-01-01   East   Apple    180

In [419]:
pivot = df.pivot_table( index='Region', columns='Product',values='Sales', aggfunc='mean')
print(pivot)


Product  Apple  Orange
Region                
East     160.0     NaN
West       NaN   135.0


In [420]:
# <!-- pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None)
# data: The DataFrame to be used.
# values: The column to aggregate.
# index: Columns to group data by (will become rows in the pivot table).
# columns: Columns to group data by (will become columns in the pivot table).
# aggfunc: The function used for aggregation (default is 'mean').
# fill_value: Replace missing values in the pivot table. -->

In [421]:
import pandas as pd
import numpy as np

data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-01'],
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Product': ['Apple', 'Orange', 'Apple', 'Orange', 'Apple'],
    'Sales': [100, 150, 200, 120, 180]
}

df = pd.DataFrame(data)
pivot = df.pivot_table(values='Sales', index='Region', columns='Product', aggfunc=np.sum, fill_value=0)
print(pivot)


Product  Apple  Orange
Region                
East       480       0
West         0     270


In [422]:
import numpy as np

data = {
    'Date': ['2023-01-01', '2023-01-01', '2023-01-02', '2023-01-02', '2023-01-01'],
    'Region': ['East', 'West', 'East', 'West', 'East'],
    'Product': ['Apple', 'Orange', 'Apple', 'Orange', 'Apple'],
    'Sales': [100, 150, 200, 120, 180],
    'Profit': [10, 15, 20, 12, 18]
}

df = pd.DataFrame(data)

pivot = df.pivot_table(values=['Sales', 'Profit'], index=['Region', 'Date'], columns='Product', aggfunc=np.sum, fill_value=0)
print(pivot)


                  Profit        Sales       
Product            Apple Orange Apple Orange
Region Date                                 
East   2023-01-01     28      0   280      0
       2023-01-02     20      0   200      0
West   2023-01-01      0     15     0    150
       2023-01-02      0     12     0    120


In [423]:
# Example 1: Concatenating DataFrames along Rows (axis=0)

import pandas as pd

# Sample DataFrames
data1 = {'A': [1, 2], 'B': [3, 4]}

data2 = {'A': [5, 6], 'B': [7, 8]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)


# Concatenating along rows (axis=0)
result = pd.concat([df1, df2],axis = 0)
print(result)
# df2

   A  B
0  1  3
1  2  4
0  5  7
1  6  8


In [424]:
# Example 2: Concatenating DataFrames along Columns (axis=1)


# Concatenating along columns (axis=1)
result = pd.concat([df1, df2], axis=1)
print(result)

   A  B  A  B
0  1  3  5  7
1  2  4  6  8


In [425]:
# Handling Indexes during Concatenation
# By default, concat preserves the original indices. Use ignore_index=True to reset the index.
result = pd.concat([df1, df2], ignore_index=True)
print(result)


   A  B
0  1  3
1  2  4
2  5  7
3  6  8


In [426]:
# Concatenating DataFrames with Different Columns
# Concatenating DataFrames with differing columns will result in NaN values where the columns don't match.
data3 = {'c': [9, 10]}
df3 = pd.DataFrame(data3)

result = pd.concat([df1, df3], axis=0)
print(result)


     A    B     c
0  1.0  3.0   NaN
1  2.0  4.0   NaN
0  NaN  NaN   9.0
1  NaN  NaN  10.0


In [427]:
# Concatenating Along Columns with Keys (Multi-level Index)
# Using keys parameter to create a hierarchical index:
# result = pd.concat([df1, df2], keys=['df1', 'df2'])
# print(result)


In [428]:
# Pandas provides the merge function to combine DataFrames based on one or more keys. 
# Here are various examples demonstrating different types of merges:

# Inner Join
# Performing an inner join on a common column between two DataFrames:

import pandas as pd

# Sample DataFrames
data1 = {'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']}
data2 = {'ID': [1, 2, 4], 'Age': [25, 30, 28]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)



In [429]:
df1

ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie

In [430]:
df2

ID  Age
0   1   25
1   2   30
2   4   28

In [431]:

# Inner join based on 'ID'
result_inner = pd.merge(df1, df2, on='ID', how='inner')
print(result_inner)

   ID   Name  Age
0   1  Alice   25
1   2    Bob   30


In [432]:
#  Left Join
# Performing a left join:
    # Left join based on 'ID'
result_left = pd.merge(df1, df2, on='ID', how='left')
print(result_left)


   ID     Name   Age
0   1    Alice  25.0
1   2      Bob  30.0
2   3  Charlie   NaN


In [433]:
# Right Join
# Performing a right join:
    # Right join based on 'ID'
result_right = pd.merge(df1, df2, on='ID', how='right')
print(result_right)



   ID   Name  Age
0   1  Alice   25
1   2    Bob   30
2   4    NaN   28


In [434]:
# Outer Join
# Performing an outer join:
    # Outer join based on 'ID'
result_outer = pd.merge(df1, df2, on='ID', how='outer')
print(result_outer)


   ID     Name   Age
0   1    Alice  25.0
1   2      Bob  30.0
2   3  Charlie   NaN
3   4      NaN  28.0


In [435]:
# Merging on Multiple Columns
# Merging based on multiple columns:
# Sample DataFrames
data1 = {'ID': [1, 2, 3], 'City': ['New York', 'San Francisco', 'Seattle']}
data2 = {'ID': [1, 2, 4], 'City': ['New York', 'San Francisco', 'Miami'], 'Population': [8000000, 900000, 500000]}
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

# Merging on multiple columns 'ID' and 'City'
result_multi_col = pd.merge(df1, df2, on=['ID', 'City'], how='outer')
print(result_multi_col)


   ID           City  Population
0   1       New York   8000000.0
1   2  San Francisco    900000.0
2   3        Seattle         NaN
3   4          Miami    500000.0


In [436]:
# stacking refers to reorganizing or reshaping data from a wide format to a long format, 
# often involving pivoting columns into rows. You can perform stacking using the stack() function. Here are some examples:

In [437]:
# Stacking a Simple DataFrame
# Consider a simple DataFrame:
import pandas as pd

data = {
    'A': [1, 2],
    'B': [3, 4]
}

df = pd.DataFrame(data)
print(df)


   A  B
0  1  3
1  2  4


In [438]:
stacked = df.stack()
print(stacked)


0  A    1
   B    3
1  A    2
   B    4
dtype: int64


In [439]:
# Stacking a DataFrame with Multi-level Index
data = {
    'A': [1, 2],
    'B': [3, 4]
}

index = pd.MultiIndex.from_tuples([('X', 1), ('X', 2)], names=['first', 'second'])

df = pd.DataFrame(data, index=index)
print(df)


              A  B
first second      
X     1       1  3
      2       2  4


In [440]:
stacked = df.stack()
print(stacked)


first  second   
X      1       A    1
               B    3
       2       A    2
               B    4
dtype: int64


In [441]:
#  Basic Grouping and Aggregation
import pandas as pd

# Sample DataFrame
data = {
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Value': [10, 15, 20, 25, 30]
}

df = pd.DataFrame(data)





In [442]:


# Grouping by 'Category' and calculating the sum
grouped = df.groupby('Category').sum()
print(grouped)

          Value
Category       
A            60
B            40


In [443]:

# Grouping by 'Category' and applying multiple aggregation functions
grouped_multi = df.groupby('Category').agg({'Value': ['sum', 'mean', 'max']})
print(grouped_multi)


# # select sum(value) , mean(value), max(value)
# from df
# group by category ,

         Value          
           sum  mean max
Category                
A           60  20.0  30
B           40  20.0  25


In [444]:
# # select sum(value) , mean(value), max(value)
# from df
# group by category , sub category

# Grouping by multiple columns and calculating the mean
data_multi_col = {
    'Category': ['A', 'B', 'A', 'B', 'A'],
    'Subcategory': ['X', 'Y', 'X', 'Y', 'X'],
    'Value': [10, 15, 20, 25, 30]
}

df_multi_col = pd.DataFrame(data_multi_col)

grouped_multi_col = df_multi_col.groupby(['Category', 'Subcategory']).agg({'Value': ['sum', 'mean', 'max']})
print(grouped_multi_col)

                     Value          
                       sum  mean max
Category Subcategory                
A        X              60  20.0  30
B        Y              40  20.0  25


In [445]:
#  Applying Custom Functions

# Applying a custom function during grouping
def custom_function(group):
    return group['Value'].max() - group['Value'].min()

custom_result = df.groupby('Category').apply(custom_function)
print(custom_result)

Category
A    20
B    10
dtype: int64


In [446]:
#  Grouping and Transformation

# Transforming data based on groups
normalized = df.groupby('Category')['Value'].apply(lambda x: (x - x.mean()) / x.std())
print(normalized)

Category   
A         0   -1.000000
          2    0.000000
          4    1.000000
B         1   -0.707107
          3    0.707107
Name: Value, dtype: float64


In [447]:

# Creating a DataFrame with Multi-level Index

import pandas as pd

# Creating a DataFrame with a MultiIndex
arrays = [
    ['A', 'A', 'B', 'B'],
    [1, 2, 1, 2]
]

index = pd.MultiIndex.from_arrays(arrays, names=('First', 'Second'))

data = {'Values': [10, 20, 30, 40]}
df = pd.DataFrame(data, index=index)
print(df)




              Values
First Second        
A     1           10
      2           20
B     1           30
      2           40


In [448]:
# Accessing Data with MultiIndex
# Accessing a specific level of the index:
# Accessing data from the first level of the index
print(df.loc['A'])


        Values
Second        
1           10
2           20


In [449]:
# Accessing data from a specific index combination
print(df.loc[('A', 1)])


Values    10
Name: (A, 1), dtype: int64


In [450]:
# Creating MultiIndex from Cartesian Product
# Creating a MultiIndex from Cartesian product of two lists
index = pd.MultiIndex.from_product([['X', 'Y'], [1, 2]], names=('First', 'Second'))
df_cartesian = pd.DataFrame({'Values': [10, 20, 30, 40]}, index=index)
print(df_cartesian)

              Values
First Second        
X     1           10
      2           20
Y     1           30
      2           40


In [451]:
# Using unstack() and stack() to Reshape Data
# Unstacking to pivot a level of the index into columns:
# Unstacking the DataFrame
unstacked = df.unstack()
print(unstacked)


       Values    
Second      1   2
First            
A          10  20
B          30  40


In [452]:
# Stacking to convert columns back into a MultiIndex:
# Stacking the DataFrame
stacked = unstacked.stack()
print(stacked)


              Values
First Second        
A     1           10
      2           20
B     1           30
      2           40


In [453]:
# Creating MultiIndex from DataFrame columns
# Creating a MultiIndex from DataFrame columns
data = {
    'First': ['A', 'A', 'B', 'B'],
    'Second': [1, 2, 1, 2],
    'Values': [10, 20, 30, 40]
}

df_from_columns = pd.DataFrame(data)
df_from_columns.set_index(['First', 'Second'], inplace=True)
print(df_from_columns)


              Values
First Second        
A     1           10
      2           20
B     1           30
      2           40


In [454]:

# date time functions



In [455]:
import pandas as pd
# str_to_date
# Sample DataFrame
data = {
    'Date': pd.date_range('2023-01-01', periods=5)
}
df = pd.DataFrame(data)
df
# # Formatting dates in a DataFrame
df['Formatted_Date'] = df['Date'].dt.strftime('%b--')
print(df)


        Date Formatted_Date
0 2023-01-01          Jan--
1 2023-01-02          Jan--
2 2023-01-03          Jan--
3 2023-01-04          Jan--
4 2023-01-05          Jan--


In [456]:
#  Formatting Specific Date Components
# Formatting specific date components
df['Year'] = df['Date'].dt.strftime('%Y')
df['Month'] = df['Date'].dt.strftime('%b')
df['Day'] = df['Date'].dt.strftime('%d')
print(df)


        Date Formatted_Date  Year Month Day
0 2023-01-01          Jan--  2023   Jan  01
1 2023-01-02          Jan--  2023   Jan  02
2 2023-01-03          Jan--  2023   Jan  03
3 2023-01-04          Jan--  2023   Jan  04
4 2023-01-05          Jan--  2023   Jan  05


In [457]:
# Formatting Date and Time
# Formatting date and time
df['Date_Time'] = pd.to_datetime('2023-01-01 12:00:00')
df['Formatted_Date_Time'] = df['Date_Time'].dt.strftime('%Y %H:%M')
print(df)


        Date Formatted_Date  Year Month Day           Date_Time  \
0 2023-01-01          Jan--  2023   Jan  01 2023-01-01 12:00:00   
1 2023-01-02          Jan--  2023   Jan  02 2023-01-01 12:00:00   
2 2023-01-03          Jan--  2023   Jan  03 2023-01-01 12:00:00   
3 2023-01-04          Jan--  2023   Jan  04 2023-01-01 12:00:00   
4 2023-01-05          Jan--  2023   Jan  05 2023-01-01 12:00:00   

  Formatted_Date_Time  
0          2023 12:00  
1          2023 12:00  
2          2023 12:00  
3          2023 12:00  
4          2023 12:00  


In [458]:
# Custom Date Formatting
# Custom date formatting
df['Custom_Format'] = df['Date'].dt.strftime('Day: %A, Date: %d, Month: %B, Year: %Y')
print(df)


        Date Formatted_Date  Year Month Day           Date_Time  \
0 2023-01-01          Jan--  2023   Jan  01 2023-01-01 12:00:00   
1 2023-01-02          Jan--  2023   Jan  02 2023-01-01 12:00:00   
2 2023-01-03          Jan--  2023   Jan  03 2023-01-01 12:00:00   
3 2023-01-04          Jan--  2023   Jan  04 2023-01-01 12:00:00   
4 2023-01-05          Jan--  2023   Jan  05 2023-01-01 12:00:00   

  Formatted_Date_Time                                      Custom_Format  
0          2023 12:00  Day: Sunday, Date: 01, Month: January, Year: 2023  
1          2023 12:00  Day: Monday, Date: 02, Month: January, Year: 2023  
2          2023 12:00  Day: Tuesday, Date: 03, Month: January, Year: ...  
3          2023 12:00  Day: Wednesday, Date: 04, Month: January, Year...  
4          2023 12:00  Day: Thursday, Date: 05, Month: January, Year:...  
