In [1]:
# 0/p
print("sharma is a good boy")

sharma is a good boy


In [2]:
# i/p

# name = input()
# print(name , " is a good boy")

In [3]:
name = "yasmin"

print(name)
print("----")
print(name)
name = "asha" 

print(name)

yasmin
----
yasmin
asha


In [4]:
a = 7

type(a)


int

In [5]:
b = 7.5

type(b)

float

In [6]:
c = "sharma"
type(c)

str

In [7]:
d = "44-5-14"

type(d)

str

In [8]:
e = "19"
type(e)

str

In [9]:
f = 19
type(f)

int

In [10]:
#type casting

num = 19
print(type(num))

num = str(num)
print(type(num))

<class 'int'>
<class 'str'>


In [11]:
num = 19
print(num, type(num))
num = float(num) # 19.0
print(num, type(num))
num = str(num)
print(num, type(num))

19 <class 'int'>
19.0 <class 'float'>
19.0 <class 'str'>


In [12]:
# 3num = 19

In [13]:
mynameissharma = 19
my_name_is_sharma = 20
# myNameIsSharma

In [14]:
a = 9
b = 8
print(a, "__", b)

9 __ 8


In [15]:
a, b = 9,8 
print(a, "__", b)

9 __ 8


In [16]:
x, y, z = "Orange", "Banana", "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


In [17]:
x =  "Orange"
y =  "Banana"
z =  "Cherry"
print(x)
print(y)
print(z)

Orange
Banana
Cherry


In [18]:
a  = 9 
type(a)

int

In [19]:
a = [9]
type(a)


list

In [20]:
# property 1 
# index positions


a = [ 10,20,"sharma","prasad",4,45,4543,454354] # 4
a[1:8]

[20, 'sharma', 'prasad', 4, 45, 4543, 454354]

#### 

In [21]:
a[2:7:3]

['sharma', 45]

In [22]:
# mutable
a = [ 10,20,"sharma","prasad",4,45,4543,454354]
a[0] = "anusha"
print(a[7])
# b = 8
# print(b)
# c = [1,2]
# print(c)

454354


In [23]:
# mutable
a = [ 10,20,"sharma","prasad",4,45,4543,454354]
a[0] = "anusha"
a
b = 8
b
c = [1,2]
c

[1, 2]

In [24]:
a = [ 10,20,"sharma","prasad",4,45,4543,454354]
print(len(a))

8


In [25]:
a = ( 10,20,"sharma","prasad",4,45,4543,454354)
type(a)

tuple

In [26]:
# a = ( 10,20,"sharma","prasad",4,45,4543,454354)
# a[7] = 10
# a

In [27]:
a = ( 10,20,"sharma","prasad",4,45,4543,454354)

print(a, type(a))
a = list(a)
a[0]= 1
print(a, type(a))
a = tuple(a)
print(a, type(a))

(10, 20, 'sharma', 'prasad', 4, 45, 4543, 454354) <class 'tuple'>
[1, 20, 'sharma', 'prasad', 4, 45, 4543, 454354] <class 'list'>
(1, 20, 'sharma', 'prasad', 4, 45, 4543, 454354) <class 'tuple'>


In [28]:
tupledetails = ("c001", "asha","7680896860")
listdetails = [90,80,100]


In [29]:
a = {1,2,3,4,5,6,1,2,3,5,7}
a

{1, 2, 3, 4, 5, 6, 7}

In [30]:
sha = { "a" : { 
            "a.1" : 2,
            "a.2"  : [10,20,30]
            }
     ,
     
     "b" : { 
            "b.1" : {
                     "b.1.1" : 4
                    }
           }
     ,
      "c"  : {
             "c.1" : 5,
             "c.2"  : {
                         "c.2.1" : [6,55]
                      }
       }}


# sha["c"]["c.2"]["c.2.1"][0]
sha.items()

dict_items([('a', {'a.1': 2, 'a.2': [10, 20, 30]}), ('b', {'b.1': {'b.1.1': 4}}), ('c', {'c.1': 5, 'c.2': {'c.2.1': [6, 55]}})])

In [31]:
asha = [21,32,43]
asha[1] = 2000
asha


[21, 2000, 43]

In [32]:
thislist = ["apple", "banana", "cherry"]
# thislist[1:3] = ["watermelon","sharma"]
thislist[1:3]= ["watermelon"]
thislist

['apple', 'watermelon']

In [33]:
# thislist = ["apple", "banana", "cherry"]
# thislist[1:3] = 200
# thislist

In [34]:
thislist = ["apple", "banana", "cherry"]
thislist[1:3] = ["watermelon","sah"]
thislist

['apple', 'watermelon', 'sah']

In [35]:
for i in range(5) :
    print("anusha")
    print("yasmin")
    
print("sharma")


anusha
yasmin
anusha
yasmin
anusha
yasmin
anusha
yasmin
anusha
yasmin
sharma


In [36]:
a = range(5)
for i in a : 
    print(i)

0
1
2
3
4


In [37]:
for i in range(5):
    print(i)

0
1
2
3
4


In [38]:
for i in [0,1,2,3,4]:
    print(i)

0
1
2
3
4


In [39]:
for i in range(3,9):
    print(i)

3
4
5
6
7
8


In [40]:
for i  in range(9,16,2):
    print(i)

9
11
13
15


In [41]:
# for ( i = 0 , i < 5 , i ++) 
#             {

#                 print(i)
#             }
    
# print("anusha innocent ")

In [42]:
# step - 1
a = [10,20,30]

for i in a :
    print(i)

10
20
30


In [43]:
students = ["rgrtgert",134,"sharma"]
for i in students :
    print(i)

rgrtgert
134
sharma


In [44]:
#step - 2
a = [10,20,30]
#for i in [0,1,2] :
for i in range(len(a)-1,-1,-1) :# 0 1 2
    print(a[i])

30
20
10


In [45]:
students = ["rgrtgert",134,"sharma"]


for i in range(len(students)) :
    print(students[i])

rgrtgert
134
sharma


In [46]:
for i  in range(5): # 1    
    for j in range (3): # 1.1
        for k in range(2) : # 1.1.1
            print(i,j,k)
        for l in range(2) : # 1.1.2
            print(i,j,l)            
    for m in range(4) : # 1.2
        print(i,m)
    print("loop is done")

0 0 0
0 0 1
0 0 0
0 0 1
0 1 0
0 1 1
0 1 0
0 1 1
0 2 0
0 2 1
0 2 0
0 2 1
0 0
0 1
0 2
0 3
loop is done
1 0 0
1 0 1
1 0 0
1 0 1
1 1 0
1 1 1
1 1 0
1 1 1
1 2 0
1 2 1
1 2 0
1 2 1
1 0
1 1
1 2
1 3
loop is done
2 0 0
2 0 1
2 0 0
2 0 1
2 1 0
2 1 1
2 1 0
2 1 1
2 2 0
2 2 1
2 2 0
2 2 1
2 0
2 1
2 2
2 3
loop is done
3 0 0
3 0 1
3 0 0
3 0 1
3 1 0
3 1 1
3 1 0
3 1 1
3 2 0
3 2 1
3 2 0
3 2 1
3 0
3 1
3 2
3 3
loop is done
4 0 0
4 0 1
4 0 0
4 0 1
4 1 0
4 1 1
4 1 0
4 1 1
4 2 0
4 2 1
4 2 0
4 2 1
4 0
4 1
4 2
4 3
loop is done


In [47]:
# * 
# * * 
# * * * 
# * * * * 
# * * * * * 

In [48]:
for i in range(5) :
    print("* " * (int(i)+1))

* 
* * 
* * * 
* * * * 
* * * * * 


In [49]:
# *
# **
# ***
# ****
# *****

# *****
# ****
# ***
# **
# *

In [50]:
for i in range(5) :
    print("*" * (int(i)+1))
for i in range(5) :
    print("*" * (5 - int(i)))

*
**
***
****
*****
*****
****
***
**
*


In [51]:
if 10 < 5 :
    print("yes")

In [52]:
if 10 < 5 :
    print("yes")
else :
    print("no")

no


In [53]:
marks = 30

if marks > 95 :
    print("distinction")
    
elif marks > 75 :
    print("firstgrade")
elif marks > 50 :
    print("secondgrade")
    
else :
    print("passed")

passed


In [54]:
a  = 10 

while a > 5 : # true 9
    print(a) 
    a = a -  1

10
9
8
7
6


In [55]:
# * * * * *
# * * * * 
# * * * 
# * * 
# *

In [56]:
for i in range(5) :
    print("* " * (5-i))

* * * * * 
* * * * 
* * * 
* * 
* 


In [57]:
# *
# **
# ***
# ****
# *****

In [58]:
for i in range(5) :
    print("*" * (int(i)+1))

*
**
***
****
*****


In [59]:
#         *
#       **
#     ***
#   ****
# *****

In [60]:
for i in range(5) :
    print(" "* ((5-i)*2),"*" * (int(i)+1))

           *
         **
       ***
     ****
   *****


In [61]:
for i in range(4):
    print("* " * (5-i))
print("* "* 3)

* * * * * 
* * * * 
* * * 
* * 
* * * 


In [62]:
#     * 
#    **
#   ***
#  ****
# *****

In [63]:
for i in range(5):
    print(" "* (4-int(i)),"*" * (i+1))

     *
    **
   ***
  ****
 *****


In [64]:
#        * 
#       * * 
#      * * * 
#     * * * * 
#    * * * * *

In [65]:
for i in range(5) :
    print(" " * (7-int(i)),"* " * (int(i) + 1))

        * 
       * * 
      * * * 
     * * * * 
    * * * * * 


In [66]:
#  * * * * *     
#  * * * * * 
#   * * * * 
#    * * * 
#     * * 
#      * 

In [67]:
print(" ","* "* 5)
for i in range(5) :
    print(" "* (int(i) +1),"* "* (5- int(i)))

  * * * * * 
  * * * * * 
   * * * * 
    * * * 
     * * 
      * 


In [68]:
a = 10

while a > 1 :
    print(a)
    if a == 9 :
        break
    a = a - 1

10
9


In [69]:
# day - 3

In [70]:
for i  in range(5) :
    print(" " * (7 - int(i)), "* " * (int(i) + 1))

        * 
       * * 
      * * * 
     * * * * 
    * * * * * 


In [71]:
#         * 
#        * *      
#       * * * 
#      * * * * 
#     * * * * *

In [72]:
# 1
# 2 2
# 3 3 3
# 4 4 4 4
# 5 5 5 5 5

In [73]:
for i in range(5) :
    print((str(i+1)+ " ") * (int(i)+1))

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 


In [74]:
# a
# b b
# c c c
# d d d d
# # e e e e e


In [75]:
anbhu = ["a","b","c","d","e"]
for i in range(5) :
    print((anbhu[i]+" ") * (int(i)+1))

a 
b b 
c c c 
d d d d 
e e e e e 


In [76]:
for i in range(5) :
    print(" " * (2* (4-int(i))), "*" * (int(i) + 1) )

         *
       **
     ***
   ****
 *****


In [77]:
# * * * * * 
# * * * * * 
#  * * * * 
#   * * * 
#    * * 
#     * 

In [78]:
print(" *"* 5)
for i in range(5) :
    print(" " * i, "* " * (5- int(i)))

 * * * * *
 * * * * * 
  * * * * 
   * * * 
    * * 
     * 


In [79]:
# 5 5 5 5 5 

# 5 5 5 5 

# 5 5 5 

# 5 5 

# 5

In [80]:
for i in range(5) :
    print("5 " *( 5 - int(i)))

5 5 5 5 5 
5 5 5 5 
5 5 5 
5 5 
5 


In [81]:
m1 = 80
m2 = 80
name = "asha"

if m1 > 85 and m2 > 85 :
    print(name , "is qualified")
else :
    print(name , " is unqualified ")

asha  is unqualified 


In [82]:

# print("start")

# m1 = int(input("enter m1 marks"))
# print("m1 done")
# m2 = int(input("enter m2 marks"))
# name = input()

# if m1 > 85 and m2 > 85 :
#     print(name , "is qualified")
# else :
#     print(name , " is unqualified ")

In [83]:
m1 = 90
m2 = 95
name = "sharma"

if m1 > 85 and m2 > 85 :
    print(name , "is qualified")
else :
    print(name , " is unqualified ")

sharma is qualified


In [84]:
# write a functin to check 
def check (m1= 0,m2 = 0,name = "student"):
    """
    this is written by @mlv prasad
    """
     
    if m1 > 85 and m2 > 85 : # check marks
        print(name , "is qualified")
    else :
        print(name, "no qualified ")


check(m1 =  90, m2  = 95)   



student is qualified


In [85]:
# yasmin
# asha
# sharma
# anusha




In [86]:
"""
yasmin
asha
anusha
sharma

"""

'\nyasmin\nasha\nanusha\nsharma\n\n'

In [87]:
print(str(6) + "9")
print("6" + "9")

69
69


In [88]:
ans = 9 

def add (a,b) :
    global ans
    ans = a + b  
    print(ans)
    
add(7,9) 
ans = 90 
print(ans)
    


16
90


In [89]:
def myfunc():
  global x
  x = "fantastic"

myfunc()

print("Python is " + x)

Python is fantastic


In [90]:
x = "awesome"

def myfunc():
#   global x
  x = "fantastic"
    
x = "yasmin"

myfunc()

print("Python is " + x)

Python is yasmin


In [91]:
# a = 5 + 2j
# real(a)

In [92]:
# a = 5 + 2j
# x = complex(a)
# real(x)

In [93]:
x = 35e14
print(x)

3500000000000000.0


In [94]:
a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.


In [95]:
a = "Lorem ipsum dolor sit amet,consectetur adipiscing elit,sed do eiusmod tempor incididuntut labore et dolore magna aliqua."
print(a)

Lorem ipsum dolor sit amet,consectetur adipiscing elit,sed do eiusmod tempor incididuntut labore et dolore magna aliqua.


In [96]:
a = "Hello, World!"
print(len(a))

13


In [97]:
a = "Hello, World!"
a[2:5]


'llo'

In [98]:
a = [1,2,3,4,5]
a[2:5]

[3, 4, 5]

In [99]:
b = "Hello, World!"
print(b[:5])

Hello


In [100]:
b = "Hello, World!"
print(b[2:])

llo, World!


In [101]:
b = "Hello, World!"
print(b[-5:-2])

orl


In [102]:
a = "Hello, World!"
print(a.upper())

HELLO, WORLD!


In [103]:
a = "Hello, World!"
print(a.lower())

hello, world!


In [104]:
a = " Hello, World! "
print(a.strip()) # returns "Hello, World!"

Hello, World!


In [105]:
a = "Hello, World!"
print(a.replace("He", "J"))

Jllo, World!


In [106]:
a = "Hello, World! prasad! sharma"
print(a.split())

['Hello,', 'World!', 'prasad!', 'sharma']


In [107]:
a = "anusha" +" "+ "superstudent"
a

'anusha superstudent'

In [108]:
b = 6 + 9
b

15

In [109]:
quantity = 3
itemno = 567
price = 49.95
myorder = "I want {} pieces of item {} for {} dollars."
print(myorder.format(quantity, itemno, price))

I want 3 pieces of item 567 for 49.95 dollars.


In [110]:
quantity = 3
itemno = 567
price = 49.95
ans = "I want {} pieces of item {} for {} dollars"
print(ans.format(quantity, itemno,price))

I want 3 pieces of item 567 for 49.95 dollars


In [111]:
print("i 4\\5\" aaa")

i 4\5" aaa


In [112]:
a = "YasminKhan"
a.upper()

'YASMINKHAN'

In [113]:
a = "YasminKHan"
a.capitalize()

'Yasminkhan'

In [114]:
a = "YasminKHan"
# a.center()

In [115]:
a = "YasminKHan"
a.count("a")

2

In [116]:
a = "YasminKhan"
a.endswith("Khan")

True

In [117]:
a = "YasminKhan"
a.index("n")

5

In [118]:
ans = "a12 3"
for i in ans :
    if i.isspace():
        print("yes")
    else :
        print("no")

no
no
no
yes
no


In [119]:
txt = "Thank you for the music\nWelcome to the jungle"
txt.splitlines()

['Thank you for the music', 'Welcome to the jungle']

In [120]:
a = "yasminKHAN"
a.swapcase()

'YASMINkhan'

In [121]:
txt = "Welcome to my world"

x = txt.title()

print(x)

Welcome To My World


In [122]:
txt = "1"

x = txt.zfill(5)

print(x)

00001


In [123]:
txt = "Hello, welcome to my world."

x = txt.index("welcom")

print(x)

7


In [124]:
import pandas as pd

In [125]:
a = ("1","2","3","4","5")
ans = "**".join(a)
ans

'1**2**3**4**5'

In [126]:
print(bool("a"))
print(bool(10))

True
True


In [127]:
5 ** 2

25

In [128]:
7 // 2

3

In [129]:
pwd

'/kaggle/working'

file = open("example.txt", "r")
content = file.read()
print(content)
file.close()

In [130]:

a = pd.read_csv("/kaggle/input/indian-unicorn-startups-2023-june-updated/Indian Unicorn startups 2023 updated.csv")
a

No.             Company                                  Sector  \
0      1              InMobi                     Adtech - Mobile Ads   
1      2           Flipkart^                              E-Commerce   
2      3            Mu Sigma                        SaaS - Analytics   
3      4           Snapdeal*                              E-Commerce   
4      5              PayTM^             Fintech - Payments & Wallet   
..   ...                 ...                                     ...   
97    98             Purplle  E-Commerce - Personal Care & Cosmetics   
98    99         Leadsquared                              SaaS - CRM   
99   100             OneCard                  Fintech - Credit Cards   
100  101          Shiprocket         Aggregator - Logistics Services   
101  102  Molbio Diagnostics                Healthtech - Diagnostics   

     Entry Valuation^^ ($B)  Valuation ($B)     Entry             Location  \
0                      1.00            1.00  Sep/2011  Bangalore/Singapore   
1                      1.00           37.60  Feb/2012  Bangalore/Singapore   
2                      1.00            1.50  Feb/2013    Bangalore/Chicago   
3                      1.80            2.40  Oct/2014                Delhi   
4                      1.70           16.00  Feb/2015                Noida   
..                      ...             ...       ...                  ...   
97                     1.10            1.10  Jun/2022               Mumbai   
98                     1.00            1.00  Jun/2022            Bangalore   
99                     1.30            1.30  Jul/2022                 Pune   
100                    1.23            1.23  Aug/2022                Delhi   
101                    1.53            1.53  Sep/2022                  Goa   

                                      Select Investors  
0                    KPCB, Sherpalo Ventures, SoftBank  
1      Accel, Tiger Global, Naspers, SoftBank, Tencent  
2             Accel, Sequoia Capital, General Atlantic  
3    Kalaari Capital, Nexus Ventures, Bessemer, Sof...  
4    Saama Capital, Elevation Capital, Alibaba, Ber...  
..                                                 ...  
97   JSW Ventures, IvyCap Ventures, Blume Ventures,...  
98         Stakeboat Capital, Gaja Capital, WestBridge  
99   QED Investors, Matrix Partners India, Sequoia ...  
100  Lightrock India, Info Edge, Tribe Capital, Tem...  
101                             Temasek, Motilal Oswal  

[102 rows x 8 columns]

In [131]:
numbers = [11, 2, 3, 4, 5]
numbers.sort()
numbers

[2, 3, 4, 5, 11]

In [132]:
numbers = [11, 2, 3, 4, 5]
numbers.reverse()
numbers

[5, 4, 3, 2, 11]

In [133]:
name = "Global Name"

def shadow_example():
    global name
    name = "Local Name"
    print(name)

shadow_example()  # Output: Local Name

print(name)    

Local Name
Local Name


In [134]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

union_set = set1.union(set2)
intersection_set = set1.intersection(set2)
difference_set = set1.difference(set2) 
print(union_set,intersection_set ,difference_set)

{1, 2, 3, 4, 5, 6} {3, 4} {1, 2}


In [135]:
a = {1,2}
a

{1, 2}

In [136]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

union_set = set1.union(set2)
intersection_set = set1.intersection(set2)
difference_set = set2.difference(set1)
print(union_set,intersection_set ,difference_set)

{1, 2, 3, 4, 5, 6} {3, 4} {5, 6}


In [137]:
for i in range(5):
    print(" "* (2*(4- int(i))),end="")
    for j in range(i+1,0,-1):
        print(j,end= " ")
    for k in range (i):
        print(k+2,end=" ")
    print()

        1 
      2 1 2 
    3 2 1 2 3 
  4 3 2 1 2 3 4 
5 4 3 2 1 2 3 4 5 


In [138]:
a = "i am ,a good ,boy"
b = a.split(',')
"&&".join(b)

'i am &&a good &&boy'

        1
      2 1 2
    3 2 1 2 3
  4 3 2 1 2 3 4
5 4 3 2 1 2 3 4 5 

In [139]:
for i  in range(5):
    print(i+1)

1
2
3
4
5


In [140]:
for i in range(5,0,-1):
    print(i)

5
4
3
2
1


In [141]:
print("mlv")

mlv


In [142]:
ans = "asha rajan"
ans[::-1]

'najar ahsa'

In [143]:
for i in range(5):
    print(i)

0
1
2
3
4


In [144]:
for i in range(5,0,-1) :
    print(i)

5
4
3
2
1


In [145]:
def add (x,y) :  
    return x + y
add(7,8)

15

In [146]:
add = lambda x,y  : x + y 

b = add(7,8)
print(b)

15


In [147]:
x = lambda a : a + 10
print(x(5))

15


In [148]:
x = lambda a : a + 10
x(25)

35

In [149]:
x = lambda a, b : a * b
x(5, 6)

30

In [150]:
x = lambda a, b, c : a + b + c
print(x(5, 6, 2))

13


In [151]:
# def myfunc(n):
#   return lambda a : a * n

# mydoubler = lambda a : a * 2 

# print(mydoubler(11))

In [152]:
# def myfunc(n):
#   return lambda a : a * n

# mydoubler = lambda a : a * 2

# print(mydoubler(11))

In [153]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)

print(mydoubler(11))

22


In [154]:
# def myfunc(n):
#   return lambda a : a * n

# mydoubler = lambda a : a * 2
# mytripler = lambda a : a * 3

# print(mydoubler(11))
# print(mytripler(11))

In [155]:
def myfunc(n):
  return lambda a : a * n

mydoubler = myfunc(2)
mytripler = myfunc(3)

print(mydoubler(11))
print(mytripler(11))


22
33


In [156]:
class fashion():
    design = "pattern design by yasmin "
    designer = "yasmin"
    def color(self,choosecolour) :
        print("kurtha is in  ",choosecolour)
   

In [157]:
anusha = fashion()
anusha.color("red")
anusha.designer
anusha.design

kurtha is in   red


'pattern design by yasmin '

In [158]:
#anbhu = sharmahouse()
#anbhu.style("red")

In [159]:
class Sharmadesign :
    design = "italian"
    
    def __init__(self, color, size):
        self.style = color 
        self.area = size

    def beauty(self):
        print("my house is a ",self.style ," and ",self.area)

anbhu = Sharmadesign("red", 100)
anusha = Sharmadesign("blue", 30)

anbhu.design = "japanese"
del anbhu.design
anbhu.design

'italian'

In [160]:
for i in range(5):
    pass


In [161]:
class sharma :
    def size() :
        print("aa") 
    def area() :
        pass

In [162]:
age = 18
status = "Adult" if age >= 18 else "Minor"
print(status)  # Output: Adult

Adult


In [163]:
age = 18
if age >=  18:
    status = "Adult"
else  :
    status = "Minor"
print(status)

Adult


In [164]:
numbers = [1, 2, 3, 4, 5]
squared = [i ** 2 for i in numbers if i > 3  if i < 5]
print(squared)  

[16]


In [165]:
numbers = [1, 2, 3, 4, 5]
squared = []
for i in numbers :
    if i > 3 : 
        if i < 5 :
            squared.append(i**2)
squared
    

[16]

# def count_up_to(limit):
    num = 1
    while num <= limit:
        yield num
        num += 1

numbers = count_up_to(1000000)
for num in numbers:
    print(num)  # Output: 1, 2, 3, 4, 5

In [166]:
def count_up_to(limit):
    num = 1
    while num <= limit:
        
        num += 1
    return num

numbers = count_up_to(5)
# for num in numbers:
#     print(num)  # Output: 1, 2, 3, 4, 5
numbers

6

In [167]:
def countdown(start):
    while start > 0:
        yield start
        start -= 1

count = countdown(3)
for num in count:
    print(num)  # Output: 3, 2, 1

3
2
1


In [168]:
squares = (x ** 2 for x in range(1, 6))
for square in squares:
    print(square)  # Output: 1, 4, 9, 16, 25

1
4
9
16
25


In [169]:
class avs:
    def __init__(self,name,age):
        self.name = name
        self.age = age
        
x =  avs("sharma",35)
print(x.name)
print(x.age)

sharma
35


In [170]:
# a = [10 ,15 ,17,20]

# ans = list (filter(lambda x : x %2 , a ))
# ans

In [171]:
ans = [ 10, 20 , 30]

sharma 

__main__.sharma

In [172]:
a = 10 


if a > 5 :
    print("yes")
else :
    print("no")

yes


In [173]:
a = 10
sharma = "yes"  if a > 5 else  "no"
sharma

'yes'

In [174]:
anbhu = lambda x,y  :  x+ y
anbhu(10,20)

30

In [175]:
array_nums1 = [1, 2, 3, 5, 7, 8, 9, 10]
array_nums2 = [1, 2, 4, 8, 9]
print("Original arrays:")
print(array_nums1)
print(array_nums2)
result = list(filter(lambda x: x in array_nums1, array_nums2)) 
print ("\nIntersection of the said arrays: ",result)


Original arrays:
[1, 2, 3, 5, 7, 8, 9, 10]
[1, 2, 4, 8, 9]

Intersection of the said arrays:  [1, 2, 8, 9]


In [176]:
# class myfunc():
#     z = 300
#     def myinnerfunc():
#         print(z)
#     myinnerfunc()

# myfunc()


In [177]:
class exam :
    sharmastd = 90
    ashastd   = 80 
    anushastd = 75
    anbhustd = 90 
    student =  ["asha","sharma","anusha","anbhu"]
    
    def __init__ (self,given,studentname  ):
        self.mlvmarks  = given
        self.result = studentname + "has got " + str(self.mlvmarks)
        self.studentname = studentname
        self.student1 = ["asha","sharma","anusha","anbhu"]
        self.marks =   [80,90,75,90] 
        
    def review(self,year) :
        for i in range(len(self.student)) :
            if self.student1[i] == self.studentname :                 
                if self.mlvmarks >  self.marks[i] :
                    return str(year) + " result is very good" 
                else :
                    return str(year)  + " result is rewrite exam"
                
anusharesult = exam(80,"anusha")
anusharesult.review(2023)

# anbhuresult = exam(65,"anbhu")
# print(anusharesult.mlvmarks," ",anusharesult.anushastd," " ,anusharesult.result," ",anusharesult.review())
# print(anbhuresult.mlvmarks," ",anbhuresult.anbhustd," " ,anbhuresult.result," ",anbhuresult.review())

'2023 result is very good'

In [178]:
# def anbhu(self) :
#         print("good girl")
# ans = self.anbhu()

In [179]:
class area:
    asha = 90

    def __init__(self,l,b = 50):
        self.length=l
        self.breadth=b
    def area_rec(self): 
        print('length='+str(self.length))
        print('breadth='+str(self.breadth))
    def display(self,aa):
        print(self.length*self.breadth*aa)
    def area_square(self,p,q):
        print(p*q)
# i1 = int(input()) 
# i2 = int(input())
a=area(10)
# a.area_rec()
a.asha
# a.display()

90

In [180]:
ans = [1,2,3,4]

a = [ i**2 for i in ans]
a

[1, 4, 9, 16]

In [181]:
ans = [1,2,3,4]
a = [i**2 for i in ans   ]


a

[1, 4, 9, 16]

In [182]:
ans = [1,2,3,4]
a = {  x : x**2 for x in ans}
a

{1: 1, 2: 4, 3: 9, 4: 16}

In [183]:
import numpy as np

In [184]:
a  = [1,2,3]
a

[1, 2, 3]

In [185]:
b = np.array([1,2,3])
type(b )

numpy.ndarray

In [186]:
print(np.__version__)

1.23.5


In [187]:
import pandas as pd
print(pd.__version__)

1.5.3


In [188]:

list_data = [1, 2, 3, 4, 5]
asha= np.array(list_data)
asha

array([1, 2, 3, 4, 5])

In [189]:
zeros_array = np.zeros((2,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.]])

In [190]:
# np.ones(): 
#Creates an array filled with ones.

ones_array = 60 * np.ones((2, 3)) 
# creates a 2x3 array filled with ones
ones_array

array([[60., 60., 60.],
       [60., 60., 60.]])

In [191]:
constant_array = np.full((2, 3), 60)  
constant_array 

array([[60, 60, 60],
       [60, 60, 60]])

In [192]:
range_array = np.arange(0, 10, 2) 
range_array

array([0, 2, 4, 6, 8])

In [193]:
linspace_array = np.linspace(12,22, 6) 
linspace_array

array([12., 14., 16., 18., 20., 22.])

In [194]:
random_array =  np.random.rand(3, 3)
random_array 

array([[0.28187586, 0.96375039, 0.78950391],
       [0.45187099, 0.36880842, 0.99360622],
       [0.80796958, 0.44883462, 0.14996737]])

In [195]:
random_int_array = np.random.randint(70, 90, size=(3, 3)) 
random_int_array 

array([[76, 75, 88],
       [81, 84, 79],
       [82, 80, 76]])

In [196]:
arr = np.array([[1, 2, 3, 4, 5, 6]])
arr.shape
# new_arr = arr.reshape((2, 3))

(1, 6)

In [197]:
print(arr)

[[1 2 3 4 5 6]]


In [198]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [199]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [200]:
#rr.reshape(3,2)
arr.ndim

2

In [201]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [202]:
arr = np.array([1, 2, 3], dtype=float) 
arr

array([1., 2., 3.])

In [203]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Addition
result_add = arr1 + arr2
result_add

# # Subtraction
# result_sub = arr1 - arr2

# # Multiplication
# result_mul = arr1 * arr2

# # Division
# result_div = arr1 / arr2

array([5, 7, 9])

In [204]:
arr = np.array([1, 2, 3])

arr1  = np.array([10, 10, 10])
arr + arr1

array([11, 12, 13])

In [205]:
arr = np.array([1, 2, 3])
arr + 10 

array([11, 12, 13])

In [206]:
a = np.arange(12)
a.reshape(3,4)
a
# a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [207]:
a = np.arange(12).reshape(2,6)
a.resize(6,2)
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [208]:
sharma = [[10,20,30],[40,50,60],[70,80,90]]
sharma = np.array(sharma)
sharma

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [209]:
sharma.shape

(3, 3)

In [210]:
sharma.flatten()

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [211]:
prasad = sharma.flatten()
prasad

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [212]:
anbhu = prasad
anbhu.resize(sharma.shape)
anbhu

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [213]:
import numpy as np

arr1 = np.array([[1, 2, 3],[10,20,30]])
arr2 = np.array([[4, 5, 6],[90,100,110]])
arr2



array([[  4,   5,   6],
       [ 90, 100, 110]])

In [214]:
# Concatenate the arrays horizontally
result_hstack = np.hstack((arr1, arr2))
result_hstack 


array([[  1,   2,   3,   4,   5,   6],
       [ 10,  20,  30,  90, 100, 110]])

In [215]:

# Concatenate the arrays vertically
result_vstack = np.vstack((arr1, arr2))
result_vstack 


array([[  1,   2,   3],
       [ 10,  20,  30],
       [  4,   5,   6],
       [ 90, 100, 110]])

In [216]:

# Concatenate the arrays along the first axis
result_concat = np.concatenate((arr1, arr2))
result_concat 

array([[  1,   2,   3],
       [ 10,  20,  30],
       [  4,   5,   6],
       [ 90, 100, 110]])

In [217]:
import numpy as np

arr = np.array([[1, 2, 3],[ 4, 5, 6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])

# Split the array into three sub-arrays
result_split = np.split(arr, 3)
result_split 


[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [218]:

result_vsplit = np.vsplit(arr, 3)
result_vsplit 

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [219]:

result_vsplit = np.hsplit(arr, 3)
result_vsplit 

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [220]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
a
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [221]:
a + b

array([[ 8, 10, 12],
       [14, 16, 18]])

In [222]:
c= np.array([[7,8,9]])

In [223]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4], [5]])
result1 = arr1 + arr2
result1

array([[5, 6, 7],
       [6, 7, 8]])

In [224]:
arr1.shape

(1, 3)

In [225]:
arr2.shape

(2, 1)

In [226]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
stacked_arr = np.stack((arr1, arr2))
print(stacked_arr)

[[1 2 3]
 [4 5 6]]


In [227]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
mask = np.where(arr > 2, arr, 0)
print(mask)

[0 0 3 4 5]


In [228]:
import numpy as np

arr1 = np.array([True, True, False, False])
arr2 = np.array([True, False, True, False])
result = np.logical_or(arr1, arr2)
print(result)

[ True  True  True False]


In [229]:
arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
print(condition)

[False False False  True  True]


In [230]:
arr = np.array([1, 2, 3, 4, 5])
boolean_arr = arr == 3
print(boolean_arr)

[False False  True False False]


In [231]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
condition = arr > 3
filtered_arr = arr[condition]
print(filtered_arr)

[4 5]


In [232]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
condition1 = arr > 2
condition2 = arr < 5
combined_condition = condition1 & condition2
filtered_arr = arr[combined_condition]
print(filtered_arr)

[3 4]


In [233]:
import numpy as np

mask1 = np.array([True, False, True, False])
mask2 = np.array([True, True, False, False])
combined_mask = mask1 & mask2
print(combined_mask)

[ True False False False]


In [234]:
import numpy as np

mask1 = np.array([True, False, True, False])
mask2 = np.array([True, True, False, False])
combined_mask = mask1 | mask2
print(combined_mask)

[ True  True  True False]


In [235]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])
mask1 = arr1 > 2
mask1


array([False, False,  True,  True,  True])

In [236]:
mask2 = arr1 % 2 == 0
mask2


array([False,  True, False,  True, False])

In [237]:
combined_mask = mask1 & mask2
combined_mask


array([False, False, False,  True, False])

In [238]:
filtered_arr = arr[combined_mask]
print(filtered_arr)

[4]


In [239]:
import numpy as np

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)
# Or, equivalently: result = matrix1 @ matrix2

print(result)

[[19 22]
 [43 50]]
